### ISSUE TITLE
What test data to use?

### ISSUE THREAD

**Issue by sydekumf** [netresearch/dhl-module-shipping-m2#1]
What test data for system configuration should I use? In order to generate a shipping label I need a valid IBAN, BIC etc. The module is set to sandbox mode. Thanks :-)

**Comment by ngolatka** [comment]
@sydekumf The Sandbox mode only allows connecting to the DHL webservice using hard-coded test credentials. The bank account data is not included in that. That means: for testing, you need to enter some valid IBAN and BIC (e.g. your own).

Not sure if there are "dummy" bank data available somewhere.
