### ISSUE TITLE
Falsche Produktauswahl bei Label Internation

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#13]
Hallo @ngolatka,

folgendes ist mir aufgefallen:

Wir haben in der Konfiguration -> Participation Numbers folgende Produkte analog zu den bestehenden Verträgen hinterlegt:

DHL Paket - **V01PAK** - Participation: 01
DHL Paket International - **V53WP** - Participation: 01

Wenn wir ein internationales Label drucken wollen (in dem Beispiel Belgien als Empfängerland), steht aber links im Dropdown nur _DHL Paket Connect_ zur Verfügung. Das Label lässt sich logischerweise nicht anlegen.

**Die EKP wurde im Beispiel angepasst auf 1122334455**

Shipping labels could not be created: Invalid XML: cvc-length-valid: Value '112233445555' with length = '12' is not facet-valid with respect to length '14' for type '#AnonType_billingNumberAbstractShipmentType'.

Der korrekte Wert der Anfrage müsste ja
1122334455**5301** 
sein, was auch der korrekten Zeichenzahl von 14 entspricht. Stattdessen erfolgt der Aufruf von Paket Connect ohne participation number, aber das siehst du ja selber...

Beste Grüße
Jan

**Comment by mam08ixo** [comment]
Hallo Jan @gewaechshaus, ich habe Deine Anfrage an das [Support-Team](https://github.com/netresearch/dhl-module-shipping-m2#support) weitergeleitet.

Zu Deiner Information vorab: Seit [Version 0.6.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.6.0) werden einige europäische Länder mit dem Produkt _DHL Paket Connect_ abgewickelt, nicht mehr mit dem Produkt _Weltpaket_ (DHL Paket International).

**Comment by gewaechshaus** [comment]
@mam08ixo - Danke dir... Ich bin gerade dabei das ganze weiter zu analysieren. Folgenden Artikel habe ich durchgearbeitet und noch ein Sonderzeichen im Firmennamen ( **™** was aber bisher funktionierte bzw. in DE aktuell funktioniert) gefunden.

http://dhl.support.netresearch.de/support/solutions/articles/12000027465-was-bedeutet-die-meldung-invalid-xml-cvc-length-valid-wert-mit-l%C3%A4nge-12-ist-nicht-facet-

BG
Jan

**Comment by gewaechshaus** [comment]
Die Meldung besteht auch nach entfernen des Sonderzeichens und Überprüfung der relevanten Werte auf Anzahl der Zeichen.

**Comment by ngolatka** [comment]
Hallo @gewaechshaus 
mein Kollege Mathias hat über den Support diese Antwort an Dich geschickt:

> DHL Shipping führt das Produkt "Paket Connect" ein, das für folgende Länder verwendet wird: AT, BE, LU, NL, PL, SK, CZ. 
Um dieses Produkt erfolgreich nutzen zu können, muss auch dafür eine Teilnahmenummer im Modul konfiguriert werden (Configuration → Sales → Shipping Methods → Account Data Business Customer Shipping → Participation Numbers → "DHL Paket Connect: V55PAK") 

> Solltest Du noch keine Teilnahmenummer für "Paket Connect" von DHL erhalten haben, kannst Du temporär die Produktzuordnung anpassen: Entferne die Zuordnung für das Empfängerland (https://github.com/netresearch/dhl-lib-shipping-mx/blob/0.6.0/Util/ShippingProducts.php#L54-L56), so dass die Regel für EU greift (Paket International).

Hat das geholfen? Wenn ja, bitte den Issue hier auf Github schließen.

**Comment by gewaechshaus** [comment]
@ngolatka - Ja, das ist die Lösung gewesen. Sorry für das anscheinend fehlende Feedback.
