### ISSUE TITLE
Magento 2.1.9

### ISSUE THREAD

**Issue by banalana** [netresearch/dhl-module-shipping-m2#14]
Hallo,

funktioniert die extension auch unter M 2.1.9 und oder unter 2.2.1 und wann wird endlich ein offizielles Release kommen?

Habe es versucht auf M 2.1.9 zu instalieren, beim :enable Dhl_Shipping lief alles noch gut
beim upgrade kommt die Fehlermeldung 

Fatal error: Interface 'Dhl\Shipping\Webservice\Client\GlRestClientInterface' not found in /html/app/code/Dhl/Shipping/Webservice/Client/GlRestClient.php on line 45

was nun?

**Comment by mam08ixo** [comment]
Jeweils aktuelle Angaben zur Kompatibilität sind im Abschnitt [Compatibility](https://github.com/netresearch/dhl-module-shipping-m2/tree/0.6.0#compatibility) und in der [`composer.json` des Moduls](https://github.com/netresearch/dhl-module-shipping-m2/tree/0.6.0/composer.json#L10) zu finden. Solange das Marketplace-Release nicht abgeschlossen ist, werden alle weiteren offiziellen Versionen hier auf GitHub veröffentlicht werden.

Wenn das Modul mit [composer](https://getcomposer.org/) installiert wird, werden auch alle Abhängkeiten (darunter o.g. fehlende Datei) mit installiert. Hilfestellung zur Installation von Magento-Extensions ist bspw. hier zu finden:

- [Install extensions from the command line | Magento 2 Developer Documentation](http://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions.html#update-composer-json)
- [DHL Shipping Composer Installation](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.6.0/README.md#vcs)
