### ISSUE TITLE
Uninstaller does not seem to work

### ISSUE THREAD

**Issue by amenk** [netresearch/dhl-module-shipping-m2#15]
Magento Version 2.2.0

	$ ./bin/magento module:uninstall --remove-data Dhl_Shipping
	You are about to remove code and/or database tables. Are you sure?[y/N]y
	Enabling maintenance mode
	You are removing data without a database backup.
	Removing data of Dhl_Shipping
	PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Eav\Setup\EavSetup::__construct() must implement interface Magento\Framework\Setup\ModuleDataSetupInterface, instance of Magento\Setup\Module\Setup given, called in /home/self/example/workspace/example.de/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /home/self/example/workspace/example.de/vendor/magento/module-eav/Setup/EavSetup.php:88
	Stack trace:
	#0 /home/self/example/workspace/example.de/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Eav\Setup\EavSetup->__construct(Object(Magento\Setup\Module\Setup), Object(Magento\Eav\Model\Entity\Setup\Context), Object(Magento\Framework\App\Cache\Proxy), Object(Magento\Eav\Model\ResourceModel\Entity\Attribute\Group\CollectionFactory))
	#1 /home/self/example/workspace/example.de/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Ma in /home/self/example/workspace/example.de/vendor/magento/module-eav/Setup/EavSetup.php on line 88

**Comment by mam08ixo** [comment]
Thanks Alexander, we will have a look at this.

In the meantime, please follow [the manual steps](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.6.0/README.md#drop-in-1) to clean up your instance.

**Comment by mam08ixo** [comment]
Thanks again for the report.

The uninstaller was fixed with 567916bedb6584ca25b15f42fe0914370a50342c. Due to some limitation of the platform, the uninstaller will still not work on Magento 2.1, see [README](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.8.0/README.md#composer-vcs-and-composer-artifact).
