### ISSUE TITLE
White page nach Installation v0.6.0

### ISSUE THREAD

**Issue by ghost** [netresearch/dhl-module-shipping-m2#16]
Guten Tag,
wie auch schon nach der Installation der version 0.1.0 besteht bei uns weiterhin das Problem der "weißen Seite" in der 0.6.0 version.

Nach vcs Installation wie in der Readme angegeben wird die Seite unter
_Stores/Configuration/Sales/Shipping settings_ weiterhin als weiße Seite ausgegeben ( keinerlei Inhalt außer die übliche Magento Admin Sidebar ). Die 0.1.0 version wurde vorher vollständig deinstalliert.
Bei uns läuft derzeit Magento 2.1.5...

**Andere Module sind unteranderem:**
Fooman - Same OderInvoice-Number
Itoris - Dynamic Product options
Payever - Payment integrations

**Comment by mam08ixo** [comment]
_DHL Shipping_ greift nicht in die _Shipping Settings_ Konfiguration ein.
Um das Problem einzugrenzen, prüfen Sie bitte Fehlermeldungen aus den Log-Dateien und der Browser-Konsole.

**Comment by ghost** [comment]
Whoups, mein Fehler...
Es gibt eine White page unter:
Stores/Configuration/Sales/Shipping methods

DIe Browser-Konsole gibt leider nichts aus

**Comment by mam08ixo** [comment]
Ich erwähnte auch Log-Dateien, wie sieht es damit aus (Webserver, PHP, Magento)?

**Comment by ghost** [comment]
Habe nun mal nach dem Serverlogs von Magento und den Errorlogs des Servers geschaut:
Folgende Sachen treten nach dem aufrufen der Seite auf

**Serverlogs:** 
_- keine Einträge -_

**Magento logs:**
`main.CRITICAL: Notice: Undefined index: value in /vendor/magento/framework/Data/Form/Element/Multiselect.php on line 74 [] []`

**Comment by mam08ixo** [comment]
Hallo @Streetec, _DHL Shipping_ führt drei Multiselect-Felder in der Konfiguration ein, die alle durch Core Source Models befüllt werden.

- _Shipping Methods for DHL Shipping_: [Magento\Shipping\Model\Config\Source\Allmethods](https://github.com/magento/magento2/blob/2.1.5/app/code/Magento/Shipping/Model/Config/Source/Allmethods.php#L41)
- _COD Payment Methods for DHL Shipping_: [Magento\Payment\Model\Config\Source\Allmethods](https://github.com/magento/magento2/blob/2.1.5/app/code/Magento/Payment/Model/Config/Source/Allmethods.php#L28)
- _Order Status_: [Magento\Sales\Model\Config\Source\Order\Status](https://github.com/magento/magento2/blob/2.1.5/app/code/Magento/Sales/Model/Config/Source/Order/Status.php#L44)

Falls der Log-Eintrag mit dem Problem in Zusammenhang steht, scheint eins dieser Source Models in Ihrer Installation keine Einträge zurückzuliefern.

Um sich dem Problem zu nähern, prüfen Sie die Rückgabewerte der drei oben verlinkten Methoden. Prüfen Sie außerdem, ob die _Shipping Methods_-Konfiguration korrekt angezeigt wird, sobald die von Ihnen benannten Drittanbieter-Module deaktiviert sind.

**Comment by ngolatka** [comment]
Da keine Rückmeldung erfolgte, mache ich diesen Issue zu.

Bei weiteren Fragen bzw. Support-Bedarf bitte über das [bekannte Supportportal](http://dhl.support.netresearch.de/) gehen.
