### ISSUE TITLE
Missing GlRestClientInterface

### ISSUE THREAD

**Issue by unifiedarts** [netresearch/dhl-module-shipping-m2#18]
while installing get this error:

`PHP Fatal error:  Interface 'Dhl\Shipping\Webservice\Client\GlRestClientInterface' not found in /xxxxx/htdocs/app/code/Dhl/Shipping/Webservice/Client/GlRestClient.php on line 45`

**Comment by ngolatka** [comment]
Hello @unifiedarts,
this sounds very much like an installation problem. I think the [library](https://github.com/netresearch/dhl-lib-shipping-mx) was not installed properly. That's where the [missing file](https://github.com/netresearch/dhl-lib-shipping-mx/blob/master/Webservice/Client/GlRestClientInterface.php) is stored.

I guess you just dropped the package into your Magento directory. That doesn't work in Magento 2 so easily (as opposed to Magento 1).

Please follow the instructions from the README.md to install the module completely. The recommended way is using Composer.

**Comment by unifiedarts** [comment]
@ngolatka there is no such file in your extension files. The package has been downloaded from github with all your files - pls give me a hint :-)

**Comment by ngolatka** [comment]
Hello @unifiedarts 
The file definitely exists. If you click [this link](https://github.com/netresearch/dhl-lib-shipping-mx/blob/master/Webservice/Client/GlRestClientInterface.php) (which I also included in my previous answer), you will see it.

The file is indeed not part of the dhl-module-shipping-m2 repository, it comes from the additional library [dhl-lib-shipping-mx](https://github.com/netresearch/dhl-lib-shipping-mx).
