### ISSUE TITLE
API Connection not persistent in backend

### ISSUE THREAD

**Issue by luckyduck** [netresearch/dhl-module-shipping-m2#19]
There seems to be an issue with the API Connection setting in the backend. Even when the configuration for "Business Customer Shipping" was saved, the Drop-Down switches back to DHL eCommerce Global API.

Here is a short video:

https://www.dropbox.com/s/35r6imv15u07c65/api-connection-setting.mp4?dl=0

Using: Magento 2.1.9 and dhl-module-shipping-m2:0.8.0 . Was the same in 0.6.0, though.

**Comment by mam08ixo** [comment]
Hi @luckyduck, the _API Connection_ dropdown is not a setting like you usually see in configuration sections. It acts as a **filter** for those API settings that you need for your store. The dropdown value is always preselected according to the _Shipping Origin Country_ that you configured in the _Sales → Shipping Settings_ section. So if you encounter an _API Connection_ preselected that you do not wish to use, you most likely did not configure the shipping origin properly.

I understand that this is not immediately clear and we will improve the UI in future versions. Thank you for reporting the issue.

**Comment by ngolatka** [comment]
A general FYI: the [documentation](http://dhl.support.netresearch.de/support/solutions/articles/12000023174) section 3.2.1 also explains what the dropdown does (just showing the config fields, not actually setting which API is used).
