### ISSUE TITLE
hallo

### ISSUE THREAD

**Issue by sync2013** [netresearch/dhl-module-shipping-m2#2]
ich habe module unter PHP 5.6.5, 5.6.30, PHP 7.0.18 durch composer installiert. Installation ging problemlos. In Admin Panel, wie beschrieben, habe ich Module mehrmals  mit Zugangsdaten von Intraship und Geschäftskundenportal getestet. Unter dem Rubrik von Order kommt keine Option DHL versenden. 
Test war unter Magento 2.1, 2.1.4 und 2.1.6. Immer gleich, keine Option.
die vorgänger Version für Intraship läuft unter 1.9 bis 1.9.3.2 fehlerfrei. 
Trotz Aktivierung Log-Level  erzeugt kein Logdatei.
Berechtigung für media, vendor, var  waren 644 bis 777 gestellt.
Die Daten sind mal wie DHL-Geschäftkundenportal und mal Intraship eingetragen

Mit freundlichen Grüssen

**Comment by ngolatka** [comment]
Vor dem Eröffnen eines Issues bitte immer zuerst die [WIssensdatenbank](http://dhl.support.netresearch.de/) checken. Issues auf Github sind nicht für allgemeine Supportfragen vorgesehen (und "hallo" ist kein aussagekräftiger Betreff).

Entsprechener Artikel für dieses Problem ist [dieser hier](http://dhl.support.netresearch.de/support/solutions/articles/12000027150-warum-wird-die-checkbox-paketaufkleber-erstellen-nicht-angezeigt-) (Screenshots zeigen Magento 1, aber sinngemäß gilt das Gleiche auch für Magento 2).

Falls das nicht hilft, kann über die [Wissensdatenbank](http://dhl.support.netresearch.de/) ein Supportticket erstellt werden.
