### ISSUE TITLE
Problem with shipping label creation if streetname and housenumber are not seperated by space

### ISSUE THREAD

**Issue by maschwa88** [netresearch/dhl-module-shipping-m2#20]
if the customer enters his address without a space between streetname and housenumber (for example Thisisastreetname.30) - which is allowed by form validation of Magento 2.x - then if you try to create a shipping-label in the backend the module produces a error with following message:
"Shipping labels could not be created: Hard validation error occured. Bitte geben Sie eine Hausnummer an. Die eingegebene Adresse ist nicht leitcodierbar. Bitte geben Sie eine Hausnummer an."

If you enter a space then it works. Also if problem can be temporarely fixed if the backend user modifies the address the module should be capable to to this automatically.

used Magento Version: CE 2.2.1

Update: 
http://dhl.support.netresearch.de/support/solutions/articles/12000036090-was-bedeutet-die-meldung-street-number-is-a-required-value-

But in germany it's quite common that users do not enter the space after the streetname.

Greetings,
Marc

**Comment by ngolatka** [comment]
Hello @maschwa88 
the module uses a quite complex set of Regular Expressions to try to split the house number from the street name. This works fine for the vast majority of addresses. However, we are very reluctant to change anything here because every change bears the risk of breaking the algorithm for some other (obscure) address.

Keep in mind that the module must work with worldwide addresses, and there are some very weird looking addresses in some parts of the world. It is very hard to achieve 100% perfection here.

Also, I have to say I don't agree with this statement:
> in germany it's quite common that users do not enter the space after the streetname

I actually do the tech support for the module, and I see quite the opposite. FYI: the [FAQ article you mentioned](http://dhl.support.netresearch.de/support/solutions/articles/12000036090-was-bedeutet-die-meldung-street-number-is-a-required-value-) is not from DHL, it is from us (the guys who built the module).

**Comment by maschwa88** [comment]
Dear @ngolatka 

thanks for your fast feedback! Meanwhile i got deeper in that materia and there really seems no easy solution to get all cases. Do you know how DHL checks the validation of an addres?. Is an address "not routable" if DHL does not know it positively or is it "not routable" if it doesn't match certain abstract criteria? 

Could there be a case where splitting would went wrong if we make a rule:

1) if there is string followed by number and no more => split string and number
2) if there is string followed by . followed by number and no more => split string and number

Greetings,
Marc

**Comment by xpedicion** [comment]
I don't think that it's the modules responsibility to compensate for a customer's laziness, and there are mistakes that are difficult to intercept programatically.
Consider addresses in Mannheim for example. There are some street names made up of one letter followed by a number like A1, Q5 etc. So if a customer would write L122, you (or a module that's supposed to split automatically) would never know if it is meant to be L1 22 or L12 2. And your proposal would actually result in L 122 which wouldn't be correct, anyway.

**Comment by ngolatka** [comment]
> Consider addresses in Mannheim for example. There are some street names made up of one letter followed by a number like A1, Q5 etc.

I was going to give the same example ;-) Mannheim has some really funny addresses.

In case anyone is interested: these are the dummy addresses we use for testing. I think they make the problem a bit clearer. Take these and add possible variations (meaning: user input mistakes), and you really open a can of worms...

- Wiesentcenter, Bayreuther Str. 108, 2. Stock
- Neue Straße 28 / 1.Stock
- Kirchengasse 7, 1. Stock Zi.Nr. 4
- Pallaswiesenstr. 57 App. 235
- Neue Str. 55, Whg. 3
- Apenrader Str. 16 / Whg. 3
- 13 2ème Avenue
- D 6, 2
- R4, 7
- Lieblgasse 2/41/7/21
- 1752 Oto, Iwatsukiku
- 3940 Radio Road, Unit 110
- 1101 Madison St # 600
- 1523 6th Ave
- 81, quai Charles de Gaulle
- Nafarroa Kalea 9
- Av. Libertad 53
- vanzada Errepidea 1
- 88 Century Blvd, Pudong
- Mannerheimintie 13A2
- Mannerheimintie 13 A2
- Mannerheimintie 13 A 2
- 7, place de l'Hôtel de Ville
- 488 West 57 Street
- 574 E 10th Street
- Neuhof 13/15
- No. 133 Shangdong St.
- 56, route de Genève
- No. 59 Yangfangdian Xi
- 514-3, Daechi-Dong
- San Millán, 3-10

**Comment by maschwa88** [comment]
ok, that seems complex. Nice job you have :-)
But aside from the one example (Mannheim L222) the approach mentioned in 1./2. should not get wrong with these test adresses. When we also would ask about strlen of the street for example >5 maybe we could optimize the number of not automatically recognized addresses. Any example if that can go wrong? If yes then i'll give up :-)

Thanks for your contribution so far!

**Comment by ngolatka** [comment]
You asked for it ;-)

https://en.wikipedia.org/wiki/File:Abbey_Road_sign.jpg

Splitting off the "8" would mean that it becomes the house number, but it is part of the street name.

**Comment by maschwa88** [comment]
first: thanks for the beatles :-)

but that's UK. Doesn't count for me to give up :-)

i reconsidered with my team and following ideas came up:

1) why not offering (optional to select in module backend) the possibility of a direct validation hooked on magento checkout. You may say it's not job of that extension, which is in deed fact. But on the other side it's bundled on a problem level. My focus at that point is automatization in backend for the end customer. 

From my point of view it does not make sense to develop a separate module hooked on your module and hooked on checkout module(s) which does that. (?)

2) The Regex Check in vendor/dhl/lib-shipping-mx/Util/StreetSplitter.php is based _only_ upon the parameter "streetinput". Worldwide!  There is really great potential to make that routine much more powerfull if we would also deal with localized settings. There should be additional parameters "country" and "region" to recognize region specific settings which will lead to a significant higher success-rate in automated splitting.

As an example we checked via openstreetmap-data every streetname in Baden-Württemberg in Germany. There was no single street name which could not parsed successfully with the initially mentioned parameters + strlen addon. Except "Bundesstraße X" or "Landesstraße X" (which is no address, because they are as real address splitted in "real" street names) or isolated fixed Streetnumbernames like "Hotel am Belchen 1". 

Greetings,
Marc

**Comment by ngolatka** [comment]
> but that's UK. Doesn't count for me to give up 

Sorry, but it counts for us - and I guess for all the merchants who ship worldwide using our module.

> why not offering (optional to select in module backend) the possibility of a direct validation hooked on magento checkout.

The DHL validation functionality can (to our knowledge) not be accessed via the API. The "real" validation is done by DHL when you try to create a label. They check if the address actually exists in a much more sophisticated way than our module can. Our module only prepares the data as good as possible.

> There should be additional parameters "country" and "region" to recognize region specific settings

You mean create different RegExes in our module for the various countries and regions all over the world, and switching between them depending on the destination country?

> As an example we checked via openstreetmap-data every streetname in Baden-Württemberg in Germany. There was no single street name which could not parsed successfully with the initially mentioned parameters + strlen addon. 

Did you verify what happens with all the other addresses I mentioned earlier? If that works too, then we'd be glad to see a pull request from you.

But in the end, I must say we agree with this statement from @xpedicion:

> I don't think that it's the modules responsibility to compensate for a customer's laziness,

Keep in mind that even if we somehow fixed the address that is sent to DHL, it would still remain incorrect in the Magento order, and potentially cause issues for other modules that want to process it (e.g. payment modules that do fraud detection).

**Comment by maschwa88** [comment]
>Sorry, but it counts for us - and I guess for all the merchants who ship worldwide using our module.

yes, absolutely. Seen on Plugin level it has to work worldwide.

>You mean create different RegExes in our module for the various countries and regions all over the >world, and switching between them depending on the destination country?

yes. Most of our customers are shipping about 80% of there orders in germany. In that usecase a country filter would make sense (for us).

>Did you verify what happens with all the other addresses I mentioned earlier? If that works too, then >we'd be glad to see a pull request from you.

we will try it in one shop for some time and i'll give feedback.

>Keep in mind that even if we somehow fixed the address that is sent to DHL, it would still remain >incorrect in the Magento order, and potentially cause issues for other modules that want to process it >(e.g. payment modules that do fraud detection).

that may be a problem. it seems best to find a solution directly at checkout to have congruent data.
seems not to be solved at one afternoon :-)

Thanks to you both for the very constructive feedback!

**Comment by ngolatka** [comment]
> it seems best to find a solution directly at checkout to have congruent data.

Exactly! Which brings me back to my earlier point:

> The DHL validation functionality can (to our knowledge) not be accessed via the API.

Sorry, but there's not a lot we can do in the DHL module. And again: it is not the task of the DHL module to compensate input errors or do some kind of address-autocomplete / autocorrect (there are other extensions available for that).

**Comment by MarcusWolschon** [comment]
Do you have suggestions for such address-normalisation/autocorrect/autocomplete modules?

With "XYZ Str.12" this happens in the Magento 1.9.x module every few weeks too.

**Comment by maschwa88** [comment]
Hi Marcus,

if you read the whole thread above you can see, that it is difficult to find 
a simple solution which works for all cases.

My recommendation would be to find a customer based solution. In your case you could
check if the problems could be solved by splitting "Str.xx" to "Str." + " " + "xx" at the level
of storing the data from checkout into the database. For that you have to write your
own extension.

Greetings,
Marc

**Comment by MarcusWolschon** [comment]
I found some documentation about how to add additional validation rules,
so the user can only enter addresses that this module can work with.
(No normalisation. Just validation and pushing error messages to the user.)
https://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_carrier.html

What ARE the rules an address must meet?

**Comment by ngolatka** [comment]
@MarcusWolschon there is a list of test-addresses in my [above comment](https://github.com/netresearch/dhl-module-shipping-m2/issues/20#issuecomment-365590408).

Another option (which might be simpler): you could offer a separate input field in the checkout for the housenumber, and then programmatically merge the two fields "street" and "housenumber" together with a whitespace.

**Comment by MarcusWolschon** [comment]
I didn't realize these where examples of valid addresses instead of valid and invalid ones.
Thanks.
As a first Step I'll try to create RegEx patterns and length+allowed-characters-rules from these and package up a nice module that either adds validation rules or use the Magento2 Plugin mechanism to add normalization of encountered special some cases.
(The later would also work for addresses from Amazon or Paypal Express Checkout.)
