### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by PrajapatiChirag** [netresearch/dhl-module-shipping-m2#21]
PHP Fatal error:  Uncaught Error: Class 'Dhl\Shipping\Config\BcsConfigInterface' not found in /var/www/html/magento218/app/code/Dhl/Shipping/Setup/ShippingSetup.php:106

![screenshot from 2018-02-22 19-32-15](https://user-images.githubusercontent.com/18494790/36542580-388bd292-1807-11e8-8d05-645006166ad1.png)

**Comment by ngolatka** [comment]
That file is indeed not part of this repository. It is located in the [lib-shipping-mx](https://github.com/netresearch/dhl-lib-shipping-mx), more precisley here: https://github.com/netresearch/dhl-lib-shipping-mx/blob/master/Config/BcsConfigInterface.php

Similar "issues" have been reported [here](https://github.com/netresearch/dhl-module-shipping-m2/issues/11) and [here](https://github.com/netresearch/dhl-module-shipping-m2/issues/18).

You must install both, the "regular" DHL shipping module **and** the lib.

Recommendation: read the README and follow it to the letter.

**Comment by PrajapatiChirag** [comment]
@ngolatka I cant able to Install using composer. how can I install this extension?

**Comment by ngolatka** [comment]
You definitely should install the module using Composer! If Composer does not work or is not available on your system, install it. Things are a LOT easier if you use Composer. A manual installation without Composer is not recommended, and not officially supported.

If there's really no other way, you can try this. Get these two packages:
- https://github.com/netresearch/dhl-module-shipping-m2
- https://github.com/netresearch/dhl-lib-shipping-mx

Put the content into these respective directories:
- vendor/dhl/module-shipping-m2
- vendor/dhl/lib-shipping-mx

Then go through the rest of the steps from the README to enable the module in Magento 2, flush the caches, create static files, etc.

Note that this manual procedure is not officially supported. If you run into problems with this, we won't be able to help you.
