### ISSUE TITLE
Label sizes [feature request]

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#23]
Hi @ngolatka,

are there plans to implement different output sizes for the generated pdf labels like in the M1 version?
If not, we would like to request that feature for clients using label printers.

Cheers
Jan

**Comment by ngolatka** [comment]
Hello @gewaechshaus 
the printing size is not controlled by the Magento extension, but by the settings in the DHL Business Customer Portal. Please log in with the same API user you are using in Magento, then go to the printer settings, and make the desired adjustments.

Note that the printer settings do not apply globally, but on a per-user-basis (in case you have more than one DHL login).

**Comment by gewaechshaus** [comment]
Thanks a lot!
