### ISSUE TITLE
Partial shipment

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#24]
I stumbled upon this some time ago, so I think this isn't version related in case of M2. I even don't know if this is a bug or not.

If you try to make a partial shipment, f.e. you have 3 items and want to ship out 2 in stock, you can't click on the save button, it stays disabled. The result is, you have to manage partial shipments externaly etc.  I didn't review the code, just want to report it.

Cheers
Jan

**Comment by ngolatka** [comment]
Hello @gewaechshaus 
just tested it, but it works perfectly fine. I was able to add packages in the popup and split the items into several DHL shipments. The result were two DHL labels, showing different weights (according to the items) and separate tracking numbers.

The workflow is somewhat non-intuitive though. First I added one package, then some items, then another package, then the rest of the items, then I clicked "save" and the DHL labels were created.

You could however set the item number to zero _before_ opening the popup. Does that work for you?

**Comment by gewaechshaus** [comment]
Moin @ngolatka 

bevor wir aneinander vorbeireden wechsel ich mal eben die Sprache: Also eine Sendung in 2 Packstücke aufteilen geht natürlich, aber nur wenn du direkt beide Labels generierst. Hat ein Händler jetzt einen Artikel im Warenzulauf und will die Gesamtlieferung in 2 Lieferungen splitten, wobei die 2te Sendung erst zu einem späteren Zeitpunkt rausgeht, ist das nicht möglich. Also eher eine Frage der Logik b, ist das so nicht möglich (klar du könntest ein Label auf Halde legen was unpraktikabel zu sein scheint). Also eher eine Frage der Logik bzw. des Ablaufes. 

Bis später + Schonmal danke für dein Feedback

**Comment by ngolatka** [comment]
Ah, das ist jetzt klarer! Dann gilt allerdings der letzte Satz aus meinem vorigen Kommentar.

Denn: wenn man im vorigen Workflow-Schritt sagt, dass alle Items verschickt werden sollen (was die Default-Einstellung ist), erwarten wir natürlich, dass das auch wirklich geht und alles auf Lager ist.

Dann müsste also auf der Seite "New Shipment" das Feld "Qty to Ship" durch den Bearbeiter entsprechend auf 0 gesetzt werden.

**Comment by gewaechshaus** [comment]
Das funzt nicht mit der 0... Siehst du schon am Gewicht, und anschließend auch bei show packages.

**Comment by gewaechshaus** [comment]
![grafik](https://user-images.githubusercontent.com/7628545/41144292-ba35e40c-6afc-11e8-9c20-28558fdee1e0.png)

**Comment by ngolatka** [comment]
Bei mir passt das Gewicht. Hast Du gesehen, dass es bei Dir auf "lb" steht statt auf "kg"? Dadurch wird es umgerechnet und es kommt ein krummer Wert raus.

Meine Bestellung:

![items](https://user-images.githubusercontent.com/7393538/41147097-baf57f66-6b05-11e8-9564-4c46e327fd9d.png)

Die zugehörigen separaten Shipments:

![shipments](https://user-images.githubusercontent.com/7393538/41147115-c7cbc5a6-6b05-11e8-826b-4d5eab47f5fd.png)

und eines der daraus resultierenden DHL-Label:

![label](https://user-images.githubusercontent.com/7393538/41147129-d2b5ddda-6b05-11e8-8c13-b1512e4e1bfc.png)

Das Gewicht stimmt. Der rostige Eimer wiegt 2 kg, und das Warp Plasma wiegt 4 kg. Das sind die Items, die zum o.g. DHL-Label gehören.

![catalog](https://user-images.githubusercontent.com/7393538/41147330-66d9e7ea-6b06-11e8-9918-ad9c4acc7c1f.png)

**Comment by ngolatka** [comment]
**Nachtrag:** das Gewicht steht standardmäßig auf "lb", was ein bekanntes Problem im Magento Core ist.

In späteren DHL Shipping Versionen (0.9.0 oder höher) werden wir das beheben bzw. umgehen. Die eigentliche Ursache liegt nicht im DHL-Modul, deswegen können wir da nur einen Workaround bauen.

**Comment by gewaechshaus** [comment]
@ngolatka - checke ich nicht was du meinst... Vereinfacht: Wenn ich 3 Artikel a 1kg habe, wovon ich einen später versende, stelle ich also einen Artikel auf QTY 0. Danach habe ich trotzdem 3kg auf dem Label und unter "Show packages" bzw. der dt. Übersetzung jeweils Stückzahl 1. Somit funzt das mit der 0 nicht...

**Comment by ngolatka** [comment]
Meine Bestellung enthält insgesamt 3 Items. Alles zusammen wiegt 8 kg.

Ich habe beim Erstellen des Shipments, bevor das Popup aufgeht, bei "Kryptonite" die "Qty to Ship" auf 0 gesetzt. Dadurch enthielt das Shipment nur die Items "Rusty bucket" und "Warp plasma sample", die zusammen 6 kg auf die Waage bringen.

Auf dem zugehörigen DHL-Label erscheinen genau diese 6 kg.

Das Kryptonite habe ich in einem anderen Shipment verschickt, und es hat sein eigenes DHL-Label.

Fazit für mich: alles ok.

**Comment by gewaechshaus** [comment]
Jetzt habe ich es gerafft - ich hatte im Popup eures Moduls die Menge auf 0 gesetzt, nicht im Shipment. Ich teste das jetzt nochmal alles durch, theoretisch müsste sich die Anforderung ja so abdecken lassen.

**Comment by gewaechshaus** [comment]
Kommando zurück - basiert auf meinem Fehler bzw. war mir das garnicht klar wie die Shipments sich splitten. Wieder was gelernt + Vielen herzlichen Dank!
