### ISSUE TITLE
Customs clearance dialog, can't add items

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#25]
Another long term bug ;) If you want to ship out to a country were you need to fill in the customs clearance details, you can't add any products to the shipment. As a result, all shipments to switzerland etc. are processed over the GK Portal.

![grafik](https://user-images.githubusercontent.com/7628545/41129633-4cb7d4ba-6ab3-11e8-8d0d-3e4faef8bc3a.png)

It can be related to the controller as the browsers dev console throws an error 500 on the request (add products to package button clicked)
https://www.xxxxxxxxxx.com/radmin/dhl/order_shipment/getShippingItemsGrid/order_id/4836/?isAjax=true

Cheers
Jan

**Comment by ngolatka** [comment]
@gewaechshaus 
sorry, but I can't duplicate that problem. Did you click "Add products to package" at the top right?

Here's what I see:

![popup](https://user-images.githubusercontent.com/7393538/41143190-b5913716-6af8-11e8-878a-55fccdbcf4c6.png)

... which looks ok to me, or am I missing something?

**Comment by gewaechshaus** [comment]
@ngolatka - Yes, I did click the "Add products"... So this one seems to be related to the environment as the request shouldn't return an error.

**Comment by ngolatka** [comment]
Hopefully, some log (Mage, PHP, webserver) should contain more details on that error 500.

If you find anything that points in the module's direction, please post the log output here.

**Comment by gewaechshaus** [comment]
OK

**Comment by gewaechshaus** [comment]
M 2.2.4 / nginx/ php7.1-fpm
```
2018/06/08 09:43:41 [error] 26355#26355: *6123157 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function isStatic() on boolean in /var/www/html/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:483
Stack trace:
#0 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(640): Magento\Eav\Model\Entity\Collection\AbstractCollection->addAttributeToSelect('dhl_dangerous_g...', true)
#1 /var/www/html/vendor/dhl/module-shipping-m2/Block/Adminhtml/Order/Shipment/Packaging/Grid.php(223): Magento\Catalog\Model\ResourceModel\Product\Collection->addAttributeToSelect('dhl_dangerous_g...', true)
#2 /var/www/html/vendor/dhl/module-shipping-m2/Block/Adminhtml/Order/Shipment/Packaging/Grid.php(169): Dhl\Shipping\Block\Adminhtml\Order\Shipment\Packaging\Grid->initItemAttributes()
#3 /var/www/html/var/view_preprocessed/pub/static/vendor/dhl/module-shipping-m2/view/adminhtml/templates/order/packaging/grid_bcs.phtml(1): Dhl\Shipping\Block\Adminhtml\Order\Shipment\Packaging\Grid->getCountryOfManufacture('" while reading response header from upstream, client: 77.182.234.156, server: www.irgendwoimnirgendwo.com, request: "POST /radmin/dhl/order_shipment/getShippingItemsGrid/order_id/4836/?isAjax=true HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "www.irgendwoimnirgendwo.com", referrer: "https://www.irgendwoimnirgendwo.com/radmin/admin/order_shipment/new/order_id/4836/"
```

**Comment by gewaechshaus** [comment]
Possible deprecated? Update: found https://github.com/netresearch/dhl-module-shipping-m2/blob/0a93b86486a522e61c2d27e6c4da2ad3e73486e3/Block/Adminhtml/Order/Shipment/Packaging/Grid.php#L165

https://github.com/magento/magento2/search?q=getCountryOfManufacture&unscoped_q=getCountryOfManufacture

I think you call this method for customs clearance only?

**Comment by ngolatka** [comment]
@mam08ixo Can you please check and comment on this? I cannot reproduce the problem.

**Comment by gewaechshaus** [comment]
@ngolatka - have you set the country of manufacture attribute on each of the tested products, so that none of them return empty?

**Comment by ngolatka** [comment]
@gewaechshaus Yes, the country of manufacture is set at all products.

**Comment by mam08ixo** [comment]
@gewaechshaus According to the stack trace, the `dhl_dangerous_goods_category` attribute instance cannot be loaded. Please make sure this attribute was properly created in your M2 instance:

- Stores → Attributes → Product Attributes → dhl_dangerous_goods_category
- SELECT * FROM eav_attribute WHERE attribute_code = 'dhl_dangerous_goods_category'
- See [`\Dhl\Shipping\Setup\ShippingSetup::addDangerousGoodsCategoryAttribute`](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.8.0/Setup/ShippingSetup.php#L50-L70)

**Comment by gewaechshaus** [comment]
@mam08ixo - thanks, I'll take a look at it...

**Comment by gewaechshaus** [comment]
Missing for sure...

**Comment by ngolatka** [comment]
Good to know! I'll add that to the [FAQ](http://dhl.support.netresearch.de/support/solutions/articles/12000045420) for everyone else.

**Comment by gewaechshaus** [comment]
@ngolatka @mam08ixo - we are checking what is causing this behavior as the setup file is correct etc. We just launched a db:shema-upgrade without success :)

Läuft also auf setup_module table wert löschen und setup:upgrade raus...

**Comment by gewaechshaus** [comment]
Wir schließen die Geschichte und bedanken uns herzlich... Ich gebe hier nochmal Feedback zur Ursache.
