### ISSUE TITLE
Setup:di:compile Error

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-module-shipping-m2#28]
**Bug description**
Add your description here. Include all the essential information.
When running setup:di:compile i get Fatal php error

**Steps to reproduce**
To reproduce the problem:
1. Clean Magento 2.2.5 install

2. composer config repositories.dhl-module-shipping-m2 vcs https://github.com/netresearch/dhl-module-shipping-m2.git
composer config repositories.dhl-lib-shipping vcs https://github.com/netresearch/dhl-lib-shipping-mx.git
composer require dhl/module-shipping-m2:0.9.0

3. ./bin/magento module:enable Dhl_Shipping
./bin/magento setup:upgrade

4. ./bin/magento setup:di:compile

Both directories exist:
vendor/dhl/module-shipping-m2
vendor/dhl/lib-shipping-mx

Error:
PHP Fatal error:  Class 'Task' not found in /var/www/html/magento2/vendor/dhl/module-shipping-m2/build/tasks/DockerProperties.php on line 28

**Expected behavior**
compilation works...

**Screenshots / logs**
If possible, add screenshots or logs to clarify your problem.
![image](https://user-images.githubusercontent.com/32599710/43522704-758b2aec-959a-11e8-9f33-d17096fec8a2.png)

**Environment**
 - Magento version: 2.2.5
 - PHP version: 7.1.12
 - Module version: 0.9.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x ] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by DavidLambauer** [comment]
There are two classes that try to extend the Task Class but this class does not exist in the repo. I guess you're running phing for your CI/CD Setup but the defined Classes don't even have the right namespace.

The two problem classes are:

```
\DockerGenerateEnviroments
\DockerProperties
```

I would recommend to namespace those classes and reference their parent class correctly. There is also a spelling error.

**Comment by moehrenzahn** [comment]
Hi @simonmaass,

The missing Class comes from the composer package `phing/phing`.
Because of a mixup our `build` directory was accidentally pushed to GitHub. Just remove that directory or require the `phing` package as a workaround; we will soon remove the build dir from the repo.

**Comment by DavidLambauer** [comment]
@moehrenzahn Could you remove it now and release it later? So we can include the master branch instead of a tag?

**Comment by Sebastian80** [comment]
Both - master and latest tag(0.9.0) are cleaned of build directory.
