### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-module-shipping-m2#29]
**Bug description**
When creating any shipping label an SOAP-ERROR: Parsing WSDL:
Couldn't load from 'https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl'

Yesterday everything worked fine - did anything change?

**Steps to reproduce**
To reproduce the problem:
1. Go to order
2. Click on ship and check "create shipping label"
3. Add product to parcel and click save
3. See error message ...

**Expected behavior**
Shipping label should be created in dhl geschäftskundenportal.

**Screenshots / logs**

![image](https://user-images.githubusercontent.com/32599710/44712869-16e7f100-aab2-11e8-8ab0-1d9732bb43e1.png)

Log entry in var/log/exception.log:
[2018-08-28 08:46:52] main.CRITICAL: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl' : failed to load external entity "https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl"
{"exception":"[object] (SoapFault(code: 0): SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl' : failed to load external entity \"https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl\"
at /var/www/html/magento2/vendor/dhl/module-shipping-m2/Webservice/Client/BcsSoapClient.php:111)"} []

**Environment**
 - Magento version: 2.2.5
 - PHP version: 7.1
 - Module version: 0.9.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Not a bug.
There was a temporary service disruption at DHL today between 10:00 - 11:30 CEST.

**Comment by simonmaass** [comment]
is there any way to get notified about these kind of downtimes?

**Comment by ngolatka** [comment]
Yes, by registering in DHL's Developer Portal:
https://entwickler.dhl.de/en/web/ep/welcome
