### ISSUE TITLE
Got certificate error while shipping label creation

### ISSUE THREAD

**Issue by sydekumf** [netresearch/dhl-module-shipping-m2#3]
When I want to create a shipping label in M2 backend I get the following error:
```
Shipping labels could not be created: Problem writing SAAJ model to stream: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Is this a temporary error from the DHL webservice or have I configured something wrong?

**Comment by ngolatka** [comment]
A quick Google search shows what is behind this: http://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find#12146838
Therefore: not a problem in the Magento module (and not an issue).

**Please note**: Issues on Github are not for support requests. For those, there is a [Support Portal](http://dhl.support.netresearch.de/).
