### ISSUE TITLE
Weight unit in kg

### ISSUE THREAD

**Issue by Merik95** [netresearch/dhl-module-shipping-m2#30]
**Feature description**
Default value for weight unit is lb. I think kg or "use magento weight unit settings is better 

**Reason**
The module is mainly for european DHL customers, which are using kg instead of lb

**Comment by simonmaass** [comment]
totally agree!!

**Comment by MarcusWolschon** [comment]
Sounds reasonable.

**Comment by ngolatka** [comment]
Y'all are correct, that's why we fixed this in version 0.9.0. [Release notes](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.9.0) say:

> Fixed
> * Packaging popup not respecting config defaults for preselects

If it does not work in version 0.9.0, please re-open this issue and provide details how to reproduce the problem.

**Comment by ngolatka** [comment]
See also issue #33.
