### ISSUE TITLE
Do you have DHL module support version 2.1.x ? 

### ISSUE THREAD

**Issue by thienphucvx** [netresearch/dhl-module-shipping-m2#31]
**Question**
Describe your problem or question here.

**Additional context**
Add context, screenshots, or background information here.

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [ ] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Sorry, but support for Magento 2.1 has been dropped in version 0.9.0.

As of now, there are no plans to maintain several module branches for M2.1 and M2.2. The minimum required version is currently 2.2.4.

**Comment by thienphucvx** [comment]
Thanks for the reply. Is that ok if I can use version 0.8.0 for Magento live site 2.1.10 ? Is there any major bugs are fixed in version 0.9.0 ?

**Comment by ngolatka** [comment]
You can use version 0.8.0, but there have been some changes and fixes.

The full list is in the [release notes for version 0.9.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.9.0).
