### ISSUE TITLE
lbs instead of Kg

### ISSUE THREAD

**Issue by MarcusWolschon** [netresearch/dhl-module-shipping-m2#33]
**Bug description**
For english orders, the product weight is used in "lbs" in the DHLShipping-M2 dialog.

**Steps to reproduce**
To reproduce the problem:
1.Set up  Magento 2.2.6 with dhl-module-shipping-m2 0.9.0 
2.Set Stores->Configuration->General->General->Locale Options->Weight Unit to "kgs" for Default, Website and all Views of that webside
2. Select frontend and admin-frontend to be English
3. place an order
4. try to buy postage for that order
5. The weight is the correct number for Kilogramm but the unit is "lbs"

**Expected behavior**
The weight of the combined products (+packaging) should be displayed and the selected unit is "kgs".

**Screenshots / logs**
(sorry, can't publicly post screenshots that inevitably contain customer data.)

**Environment**
 - Magento version: 2.2.6
 - PHP version: 7.1
 - Module version: 0.9.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by simonmaass** [comment]
Same issue with same setup

**Comment by ngolatka** [comment]
We actually thought that this was fixed in version 0.9.0, but I can duplicate the problem. Will check what happened here.

However, the module should still transmit the correct value (in kg) to DHL, and that should also show up on the label. Can you guys confirm that, @MarcusWolschon @simonmaass ?

**Comment by MarcusWolschon** [comment]
No, instead of 1Kg a shipping label for 0.454 kg = 1lbs was created.

**Comment by ngolatka** [comment]
Thanks for checking @MarcusWolschon. We'll take a look at it.

**Comment by ngolatka** [comment]
Confirmed: the issue was indeed resolved, but the commit got mangled later on.

This will be fixed in future versions.

**Comment by powli** [comment]
@MarcusWolschon @simonmaass fixed with [0.9.1](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.9.1)
