### ISSUE TITLE
Feature Request: Tare weight

### ISSUE THREAD

**Issue by MarcusWolschon** [netresearch/dhl-module-shipping-m2#34]
**Feature description**
Add an option "tare weight" for packaging that is added to all orders.

**Reason**
Magento itself only offers this option in the "Magento Shipping" part that is not offered in Europe and probably not compatible with DHL anyway.
So it can currently only exist in the shipping module itself.

If a merchant sells small items (in my case lightweigh sets of playing cards)
that are sold in quantities >1
then adding the weight of the packaging to each item is exsessive.

**Additional context**
A custom item "packaging" added to each shopping card can always be removed by the user.

**Comment by ngolatka** [comment]
It has been suggested to DHL to implement such a feature, but it has not been accepted yet.

It is possible that this might go into a future version, but at this time, we don't know if and when.
