### ISSUE TITLE
Problem writing SAAJ model to stream: sun.security.validator.ValidatorException

### ISSUE THREAD

**Issue by kubracikgoz** [netresearch/dhl-module-shipping-m2#35]
Hi.
When I want to create a shipping label in backend I get the following error:
**(Problem writing SAAJ model to stream: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.)**

I've tried some options on the Internet.
But it didn't work.

- [x] - I changed JAVA.
- [x] - I saved the certificate.
- [x] - I added the certificate to be reliable in Java.

Do you have any other suggestions? 

Thank you for your help..

**Comment by ngolatka** [comment]
That looks very much like a problem with the certificate, which causes the HTTPS connection to fail. A quick Google search turned up this: https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find

Sorry, but there's nothing we can do inside the DHL module to fix this.
