### ISSUE TITLE
Weight is not correctly calculated

### ISSUE THREAD

**Issue by crtl** [netresearch/dhl-module-shipping-m2#38]
**Bug description**
After upgrading to 0.9.1 the weight of a shipment is not calculated correctly based on the products weight anymore. This also causes missing warnings when total weight exceeds the dhl maximum.
Normaly the extension then said to pack the items in multiple packages.

**Steps to reproduce**
To reproduce the problem:
1. Create an order with many items which weight around 15-30kg
2. Weight is not correctly calculated (Qty is ignored)

**Expected behavior**
Weight should be calculated correctly

**Screenshots / logs**
![screenshot-maruhn shop-2018 10 18-11-40-46](https://user-images.githubusercontent.com/25827827/47145915-2f62d380-d2cb-11e8-8e94-1cc74250d70f.png)

**Environment**
 - Magento version: 2.2.4 CE
 - PHP version: 7.0
 - Module version: 0.9.1 

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x ] Yes, but couldn't find anything

**Comment by ngolatka** [comment]
Thanks for reporting that. This seems to affect the mass actions and processing via Cronjob.

We'll look into it and provide a fix in an upcoming version.

**Comment by moehrenzahn** [comment]
Hi @crtl,

thank you for your bug report. We fixed the issue; the fix will be rolled out with the next feature release, expected during the next few weeks.

Until then, you may manually correct the issue in your local code.

In the File `AutoCreate/RequestBuilder.php`, replace line 295:

```php
$totalWeight += $item->getWeight();
```

with the following:

```php
$totalWeight += $item->getWeight() * $item->getQty();
```

**Comment by ngolatka** [comment]
The new [version 0.10.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.10.0) resolves this issue.
