### ISSUE TITLE
Column 'adress_id' cannot be null

### ISSUE THREAD

**Issue by MarcusWolschon** [netresearch/dhl-module-shipping-m2#40]
**Bug description**
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'adress_id' cannot be null, query was: INSERT INTO "dhlshipping_quote_adress" (adress_id, info) VALUES (?,?)`

**Steps to reproduce**
To reproduce the problem:
1. Sadly I can not reproduce this yet. A user reported it with the above error as a quote.
2. I'll try to find out more by playing around with the specific user's address. It may be related to migrated customer address entries from Magento 1.9 using the Magento migration tool.

**Expected behavior**
Add the expected behavior. In other words: what SHOULD happen, but doesn't.

**Screenshots / logs**

I was only able to activate logging after the fact. So this ticket may stay open for a while until either other users with the same error message can chime in or this happens again and I can provide more details.

**Environment**
 - Magento version: 2.2.6
 - PHP version: 7.1
 - Module version:  0.9.1

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [ ] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by muh-nr** [comment]
Hello Marcus,

we need a proper description how the error appears and what the user was doing as well as the corresponding magento and PHP error logs.

For personal help please add a new support ticket at http://dhl.support.netresearch.de

What I can see so far is, that the field is called "adress_id" while it should be named "address_id".

Best regards
Mathias
Netresearch Support

**Comment by MarcusWolschon** [comment]
Strangely I couldn't find the 'adress_id' with the typo anywhere in the entire installation including this module.
Since no other users with similar issues came up within 3 days and it was not reproducable during extensive tests,
I'll just close it.
