### ISSUE TITLE
incompatible with your PHP version (7.1.22)

### ISSUE THREAD

**Issue by dmconnector** [netresearch/dhl-module-shipping-m2#42]
**Bug description**
I get following Error:
Package dhl/module-shipping-m2 at version 0.6.0 has a PHP requirement incom
  patible with your PHP version (7.1.22)

**Steps to reproduce**
To reproduce the problem:
Installation with composer download or github

**Expected behavior**
Add the expected behavior. In other words: what SHOULD happen, but doesn't.

**Screenshots / logs**
If possible, add screenshots or logs to clarify your problem.

**Environment**
 - Magento version: 2.2.6
 - PHP version: 7.1.22
 - Module version: 0.6.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [X] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by powli** [comment]
Hey @dmconnector,
is there a specific reason why you want to install version 0.6.0? The latest available version today is 0.9.1 (https://github.com/netresearch/dhl-module-shipping-m2/releases), where you will not experience that problem.
So if you don't have any objections against that, I'd recommend to just install the latest available version.

**Comment by dmconnector** [comment]
Thank you. Solved ;)
