### ISSUE TITLE
Cannot set Table rates CSV because change to website view not possible

### ISSUE THREAD

**Issue by itsolon** [netresearch/dhl-module-shipping-m2#43]
we have magento 2 with different websites
i can install and use dhl shipping module 
with
standard view
and storeviews
but if i want to set the csv from tablerates (standard shipping module for price display)
i have to change to
shopview otherwise the csv does not appear.
when switching to that i get

1 exception(s):
**Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Angeforderter Store wurde nicht gefunden.**

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Angeforderter Store wurde nicht gefunden.
#0 /home/xxxxxxxxx/web/xxxxxxx.com/public_html/vendor/magento/module-store/Model/StoreManager.php(167): Magento\Store\Model\StoreRepository->getById('5')
#1 /home/xxxxxxxxx/web/xxxxxxx.com/public_html/vendor/dhl/module-shipping-m2/Model/Config/ConfigAccessor.php(116): Magento\Store\Model\StoreManager->getStore('5')
#2 /home/xxxxxx/web/xxxxxxx..com/public_html/vendor/dhl/module-shipping-m2/Model/Config/ModuleConfig.php(114): Dhl\Shipping\Model\Config\ConfigAccessor-

i have to remove dhl shipping module
then edit csv for shipping
and then activate shipping module haha -- not intended, Right?

**Comment by ngolatka** [comment]
Hello @itsolon 
no, that's indeed not how it should be. We are aware of this problem. It affects versions 0.9.0 and 0.9.1.

The fix is currently in QA and will be included in future versions.

**Comment by itsolon** [comment]
Thank you very much for your fast Feedback. At the first moment someone – in this case me – thinks the reason must be something else..
Im happy that i can look forward to the next Version of dhl shipping

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Norman Golatka <notifications@github.com>
Gesendet: Tuesday, December 4, 2018 8:12:22 AM
An: netresearch/dhl-module-shipping-m2
Cc: Markus Peikert; Mention
Betreff: Re: [netresearch/dhl-module-shipping-m2] Cannot set Table rates CSV because change to website view not possible (#43)


Hello @itsolon<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fitsolon&data=02%7C01%7C%7Cf0228933590b4957e1bf08d659b7d742%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636795043452555133&sdata=H%2BtF1gVazl5vJlcLoXHKZ6kPQmph3bGQMS%2BPPx4xH%2F0%3D&reserved=0>
no, that's indeed not how it should be. We are aware of this problem. It affects versions 0.9.0 and 0.9.1.

The fix is currently in QA and will be included in future versions.

**Comment by ngolatka** [comment]
The new [version 0.10.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.10.0) resolves this issue.
