### ISSUE TITLE
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Angeforderter Store wurde nicht gefunden.

### ISSUE THREAD

**Issue by ghost** [netresearch/dhl-module-shipping-m2#45]
Re: DHLSUP-1046263: website/store verwechslung

DHL Support (Netresearch) <dhl.support@netresearch.de>
18:29 (vor 0 Minuten)
an mich

Thank you, we have received your request and will get back to you shortly. Your ticket number is DHLSUP-1046263.

-—————————

Vielen Dank, Ihre Anfrage ist bei uns eingegangen. Wir melden uns in Kürze bei Ihnen. Ihre Ticket-Nummer ist DHLSUP-1046263.

-—————————

Netresearch DTT GmbH
Nonnenstraße 11c – 04229 Leipzig – Germany
Registergericht: AG Leipzig HRB 34690
Geschäftsführer: Thomas Wilhelm

Netresearch GmbH & Co. KG
Nonnenstraße 11d – 04229 Leipzig – Germany
Registergericht: AG Leipzig HRA 15614
Komplementär: Netresearch Beteiligungs GmbH, AG Leipzig HRB 17018
Geschäftsführer: Thomas Fleck
—

Matthias Büsing wrote:

Moin,
ich habe einen kleiner aber sehr nervigen Bug gefunden im DHL Modul für Magento 2.
Magento ist Version 2.2.6, DHL Modul hat Version 0.9.1

Exception wird geworfen:
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Angeforderter Store wurde nicht gefunden.

Stack Trace:

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Angeforderter Store wurde nicht gefunden.
#0 /home/matthias/htdocs/XXX/vendor/magento/module-store/Model/StoreManager.php(171): Magento\Store\Model\StoreRepository->getById('6')
#1 /home/matthias/htdocs/XXX/vendor/dhl/module-shipping-m2/Model/Config/ConfigAccessor.php(116): Magento\Store\Model\StoreManager->getStore('6')
#2 /home/matthias/htdocs/XXX/vendor/dhl/module-shipping-m2/Model/Config/ModuleConfig.php(114): Dhl\Shipping\Model\Config\ConfigAccessor->getConfigValue('shipping/origin...', '6')
#3 /home/matthias/htdocs/XXX/vendor/dhl/module-shipping-m2/Model/Config/ModuleConfig.php(348): Dhl\Shipping\Model\Config\ModuleConfig->getShipperCountry('6')
#4 /home/matthias/htdocs/XXX/vendor/dhl/module-shipping-m2/Block/Adminhtml/System/Config/Form/Field/ApiType.php(87): Dhl\Shipping\Model\Config\ModuleConfig->getApiType('6')

Geht los bei:
Dhl\Shipping\Block\Adminhtml\System\Config\Form\Field\ApiType
in Zeile 86 wird die website-ID aus den GET Parametern geholt, in Zeile 87 wird damit die Methode getApiType angesprochen.
Diese erwartet jedoch eine store-ID und dann sol im weiteren Verlauf dann der Store mit der Webseiten-ID geladen werden.
Das fällt nicht weiter auf, solange die Website mit der 1 geladen werden soll, denn meist gibt es ja auch den Store 1.
In unserem Fall aber nicht - und darum geht das ganze kaputt.

Das Ganze lässt sich so replizieren:
AdminPanel>Shops>Konfiguration>Umsatz>Versandmethoden und dort einmal über die StoreView Auswahl einen Webseite auswählen die nicht die 1 ist.

in unserem Fall sieht man dann in der URL: /website/6/

Wäre schön, wenn Sie das einmal prüfen und ggf. ASAPST fixen könnten. Danke.

**Comment by ngolatka** [comment]
Hi @mb-tec , our team replied to your support case DHLSUP-1046263 on 22 Nov 2018 at 12:12 PM.

In short: we are aware of the problem and will provide a fix in the next release.

Note: this is the same as issue #43. I'm closing this one (#45) because it's essentially a duplicate.
