### ISSUE TITLE
Cannot install DHL module 0.9.1 with lib-shipping-mx 0.10.0

### ISSUE THREAD

**Issue by ngolatka** [netresearch/dhl-module-shipping-m2#49]
**Bug description**
The dhl-module-shipping-m2 **0.9.1** cannot be installed with the currently available [lib-shipping-mx](https://github.com/netresearch/dhl-lib-shipping-mx) **0.10.0**.

This results in PHP Fatal Errors during installation, for example:

> PHP Fatal error: Declaration of Dhl\Shipping\Webservice\Client\BcsSoapClient:: getVersion(Dhl\Shipping\Bcs\Version $request) must be compatible with Dhl\Shipping\Webservice\Client\BcsSoapClientInterface:: getVersion(Dhl\Shipping\Webservice\Schema\Bcs\Version $part1)
...

----

**Cause**
This is a known problem. Because of the too loose version requirements in the composer.json of dhl-module-shipping-m2, Composer tries to install lib-shipping-mx 0.10.0, which is unfortunately too new and not backwards compatible.

Library version 0.9.0 is needed for dhl-module-shipping-m2 0.9.1

----

**Workaround option 1**
Requiring `"dhl/lib-shipping-mx": "0.9.0"` **explicitly in the project's root composer.json** lets you get around this problem, so you can install the DHL module.

**Workaround option 2**
Instead of using the Github repository, install the module and the library using these ZIP files:
* https://dhl-sharing.nrdev.de/modules/versenden-shipping/mage2/dhl-module-shipping-m2-0.9.1.zip
* https://dhl-sharing.nrdev.de/modules/versenden-shipping/mage2/dhl-lib-shipping-mx-0.9.0.zip

Follow the instructions in the [README.md](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.9.1/README.md) chapter "_Installation Instructions -> Artifact_".

**Workaround option 3**
Install the DHL module using Packagist. Do **not** execute this command:
`composer config repositories.dhl-lib-shipping vcs https://github.com/netresearch/dhl-lib-shipping-mx.git`
The library 0.10.0 has been delisted from Packagist. You will therefore get library version 0.9.0, which works.

----

**Clean solution**
As soon as dhl-module-shipping-m2 0.10.0 is released, the above problem will disappear. We are working on that release together with DHL with high priority, see issue #44.

----

**And finally:**
_We're really sorry for the trouble this may cause! [Contact our support](http://dhl.support.netresearch.de/support/tickets/new) if you have any questions._

**Comment by ngolatka** [comment]
**Addendum**
We have delisted the lib-shipping-mx 0.10.0 from Packagist. If you are installing the DHL module using Packagist, you should not run into the above issue.

**Comment by gewaechshaus** [comment]
Big thanks!

Greetings
Jan

**Comment by ngolatka** [comment]
The new DHL Shipping [version 0.10.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.10.0) is now available, which resolves this issue.
