### ISSUE TITLE
Is the DHL API down?

### ISSUE THREAD

**Issue by ngolatka** [netresearch/dhl-module-shipping-m2#50]
This is not a real issue, more like a general FYI for everyone:

If you are wondering "_Is the DHL API down?_", have a look at [this article in the Knowledge Base](http://dhl.support.netresearch.de/support/solutions/articles/12000049123).

It shows the status of the sandbox and production APIs for:
* DHL Business Customer Shipping (used for creating shipping labels)
* Parcelmanagement API (for additional DHL services in the checkout)

Hint: You can also register in the [DHL Developer Portal](https://entwickler.dhl.de/en/web/ep/welcome) to get notified via email about outages and upcoming changes.

**Comment by MarcusWolschon** [comment]
Feature Request: Add a link to http://dhl.support.netresearch.de/support/solutions/articles/12000049123 into error messages

**Comment by ngolatka** [comment]
@MarcusWolschon There's roughly one metric crapton of possible error messages, and only a very small subset of them would actually be caused by an API outage.

**Comment by MarcusWolschon** [comment]
Only the one(s) that comes up if the API can not be contacted of cause.
(Things often do seem to be down when working on weekends late at night.)
Not the many error codes the working API could return.

**Comment by ngolatka** [comment]
Frankly, I think the necessary effort is not justified. Sorting error messages into "_API down yes / no_" categories to decide if the link should be displayed seems a bit overkill.

The DHL API does not fail _that_ often (maybe once every few months, if that).

If something doesn't work, the [Knowledge Base](http://dhl.support.netresearch.de) should be the first point of contact anyway, and the article about the API status is on the start page in the top five.
