### ISSUE TITLE
Can't install with PHP 7.2.13

### ISSUE THREAD

**Issue by ramzdam** [netresearch/dhl-module-shipping-m2#52]
**Bug description**
Can't install the version 0.10.0 via VCS eventhough my PHP version is 7.2.13

**Steps to reproduce**
To reproduce the problem:
1. Run command `composer require dhl/module-shipping-m2:0.10.0` 
2. An error is displayed and installation fails

**Expected behavior**
Should install successfully since I have PHP version 7.2.13

**Screenshots / logs**
  [InvalidArgumentException]
  Could not find package dhl/module-shipping-m2 in any version matching your PHP version (7
  .2.13)

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Environment**
 - Magento version: Magento ver. 2.3.0
 - PHP version: PHP 7.2.13
 - Module version: 0.10.0
 - OS: CentOS

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [ x ] Yes, but couldn't find anything
- [  ] Yes, but solution did not work

**Comment by mam08ixo** [comment]
Version 0.10.0 is [compatible with PHP 7.2](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.10.0/composer.json#L8).

Installation runs through with no issues.
![dhl-shipping-install](https://user-images.githubusercontent.com/1771622/54161399-46f55100-4452-11e9-87a6-2e4c62f3de78.png)


Check if your [composer version](https://getcomposer.org/download/) is up-to-date or if there are any CentOS related issues with it.

**Comment by ramzdam** [comment]
Thanks for this I guess the README.md is somewhat a little misleading specially for a newby like me. I followed the instruction

> composer require dhl/module-shipping-m2:0.10.0 

for VCS but didn't know that I have to run the

> composer config repositories.dhl-shipping-m2 vcs git@github.com:netresearch/dhl-module-shipping-m2.git

**Comment by ngolatka** [comment]
Hint for anybody who also runs into this: the FAQ http://dhl.support.netresearch.de contains info on what needs to be done. Search for "_Could not find package_".

I'm mentioning this because @ramzdam wrote "_Has the Knowledge Base been checked for a solution? Yes, but couldn't find anything_". The info is in fact [there](http://dhl.support.netresearch.de/support/solutions/articles/12000027852).

**Comment by MarcusWolschon** [comment]
Searching for "Could not find package" you get
http://dhl.support.netresearch.de/support/solutions/articles/12000027852-what-does-the-message-could-not-find-package-mean-
refering to
http://support.netresearch.de/support/solutions/articles/12000008579

and both don't say anything about "composer config repositories.dhl-shipping-m2 vcs ..."

**Comment by ngolatka** [comment]
@MarcusWolschon Yep, I noticed. that's why I removed my earlier comment.

We'll amend the readme to make this clearer.
