### ISSUE TITLE
Cannot create return label (Beilegeretoure)

### ISSUE THREAD

**Issue by ngolatka** [netresearch/dhl-module-shipping-m2#53]
**Bug description**
Selecting "_Return shipment_" in the popup for creating a DHL label has no effect. No Return Label  (Beilegeretoure) is created, only a "regular" shipping label.

**Steps to reproduce**
1. In the DHL configuration in Magento, set the option "_Use Return Shipment Service_" to "_No_".
2. Open an order and create a new DHL shipment.
3. In the "_Create packages_" popup, enable the checkbox "_Return Shipment_" and confirm.
4. Open the DHL label (PDF). There is no second page with the Return Label.

The checkbox in the "_Create packages_" popup has no effect. The setting is always taken from the configuration option "_Use Return Shipment Service_".

**Expected behavior**
The checkbox should have an effect and override the default configuration.

**Environment**
 - Module version: 0.10.1

**Comment by ngolatka** [comment]
This is a **known issue in version 0.10.1**. It will be fixed in future versions.

As a workaround, you can set the configuration option "_Use Return Shipment Service_" to "_Yes_". This will always create a Return Label for every shipment.

**Comment by moehrenzahn** [comment]
This should be fixed in today's 0.10.2 release: https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.10.2
