### ISSUE TITLE
Cannot select Visual Check Of Age (Altersichtprüfung) in shipping popup

### ISSUE THREAD

**Issue by ngolatka** [netresearch/dhl-module-shipping-m2#55]
**Bug description**
When creating a shipment manually via the "_Create packages_" popup, the dropdown for the service _Visual Check Of Age_ contains no elements. The expected entries "_A16_" and "_A18_" are not there, it only says "_Please select_".

**Expected behavior**
The dropdown menu should contain the entries "_A16_" and "_A18_".

**Example screenshot**
![age_verification](https://user-images.githubusercontent.com/7393538/55866195-20752380-5b80-11e9-9b75-9e4b2bc43a46.png)

**Environment**
 - Module version: 0.10.1

**Comment by ngolatka** [comment]
This is a **known issue in module version 0.10.1**. It will be fixed in future versions.

Workaround: create the shipments via mass-action or Cronjob, and set the desired service (A16 or A18) in the module configuration "_Use Visual Check of Age Service_" in Magento.

**Comment by moehrenzahn** [comment]
This should be fixed by today's 0.10.2 release: https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.10.2
