### ISSUE TITLE
Allow creation of postage for forgotten shipment-items

### ISSUE THREAD

**Issue by MarcusWolschon** [netresearch/dhl-module-shipping-m2#56]
**Change description**
If an item was forgotten in a shipment, it should be possible to create the postage in Magento.

**Reason**
The address data and product weights already exist in Magento.
To do this manually in http://dhl-geschaeftskundenportal.de/ not only is cumbersome but also very
error prone.

**Additional context**
steps:
1. create order for 2 items
2. create shipment for 2 items
3. try to create second postage for the existing shipment
4. you are forced to select a product
5a. if a product is selected that is already shipped, the "save" button is disabled.
5b. Instead there should just be a warning or confirmation.

**Comment by mam08ixo** [comment]
To recap the situation: While creating shipment and label in Magento, you included all of the ordered items. From a Magento perspective, the shipment is now complete. Then, during picking & packing, you did not put all ordered items into the box for whatever reason, so you need another shipping label to ship the remaining items.

This is possible by opening the previously created shipment in Magento admin panel and clicking the _Create Shipping Label..._ button in the _Shipping and Tracking Information_ section.

> if a product is selected that is already shipped, the "save" button is disabled.

I believe that's not the reason. The actual reason for the "Save" button being disabled in packaging popup is that you did not assign all the shipment's items to packages. You will have to include the already dispatched item again to re-create the label. There are a few downsides though:

- The previous shipping label will be replaced in Magento
- You have to adjust the total weight manually to match only the remaining item's weight.
- Customs declarations for cross-border shipments will include all items, even though you pick&pack only the remaining items.

All of the described behaviour is Magento core, DHL Shipping does not interfere with that, so this is as good as it gets. If you can live with the downsides mentioned above, then this is still more convenient than creating the new label through the Portal. Hope that helps.

**Comment by MarcusWolschon** [comment]
Thanks.
I did not even think about adding products that would not be a part of that second shipment.
