### ISSUE TITLE
Tracking number not stored in M2, label successfully in DHL portal created

### ISSUE THREAD

**Issue by Napfton** [netresearch/dhl-module-shipping-m2#58]
**Bug description**
After upgrading to M2 2.2.8 when creating a shipping label we always get "Shipment with requested ID  doesn't correspond with Order with requested ID 1." but label was successfully created in DHL portal but M2 doesnt get it or doesnt store it.

**Steps to reproduce**
To reproduce the problem:
1. Open order
2. Click Ship
3. Add shipping label
4. Add products, weight etc to package
5. Click Save
6. See "Shipment with requested ID  doesn't correspond with Order with requested ID 1."

**Expected behavior**
Tracking number stored in magento.

**Screenshots / logs**

**Environment**
 - Magento version: 2.2.8
 - PHP version: 7.0.33-0+deb9u3
 - Module version: 0.10.1

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [X] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Hello @Napfton, you wrote

> After upgrading to M2 2.2.8 ...

1. Which Magento version did you use before the upgrade?
2. Has anything else been updated in the shop?
3. Can you please test with a non-DHL shipping method if the same problem occurs?
4. To be on the safe side: can you update to the latest version (currently 0.10.2) and test again?

I tested it locally, but I don't see this problem. The shipment + label get stored in Magento correctly.

One thing that looks odd: there is no shipment ID in your error message. There should be one, but it seems to be empty.

**Comment by Napfton** [comment]
1. 2.2.6
2. No
3. We have no non-DHL shipping method
4. Will do

I omitted that for googleing purposes, but forgot to re-enter it here. Its definitely there and correct, what makes me wonder is the 1 at the end, shouldnt this be a different ID as well?

**Comment by powli** [comment]
Hello @Napfton,

can you please specify the route you want to send the package over, so basically origin country and destination country?

**Comment by Napfton** [comment]
Both Germany but also other EU destinations same result.

**Comment by Napfton** [comment]
Hm, unable to upgrade to 0.10.2:
$ composer require dhl/module-shipping-m2:0.10.2
./composer.json has been updated
Loading composer repositories with package information                                                                                                                             Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove dhl/lib-shipping-mx 0.11.0
    - Installation request for dhl/module-shipping-m2 0.10.2 -> satisfiable by dhl/module-shipping-m2[0.10.2].
    - Conclusion: don't install dhl/lib-shipping-mx 0.11.0
    - Conclusion: don't install dhl/lib-shipping-mx 0.11.0
    - dhl/module-shipping-m2 0.10.2 requires dhl/lib-shipping-mx ^0.11.1 -> satisfiable by dhl/lib-shipping-mx[0.11.1].
    - Can only install one of: dhl/lib-shipping-mx[0.11.1, 0.11.0].
    - Can only install one of: dhl/lib-shipping-mx[0.11.0, 0.11.1].
    - Installation request for dhl/lib-shipping-mx (locked at 0.11.0) -> satisfiable by dhl/lib-shipping-mx[0.11.0].

**Comment by powli** [comment]
>- Installation request for dhl/lib-shipping-mx (locked at 0.11.0) -> satisfiable by dhl/lib-shipping-mx[0.11.0].

Do you maybe have the library as a direct dependency in your projects composer.json?

**Comment by ngolatka** [comment]
@Napfton 

> We have no non-DHL shipping method

Could you enable a dummy shipping method, NOT link it to DHL, and then create a test order yourself? Maybe use "Flat Rate" or "Free Shipping".

It would be interesting to see if the problem always occurs, regardless of our DHL module. You could do that before fighting with Composer to get the module updated (and then maybe find that the update didn't help).

**Comment by Napfton** [comment]
@powli 

> > * Installation request for dhl/lib-shipping-mx (locked at 0.11.0) -> satisfiable by dhl/lib-shipping-mx[0.11.0].
> 
> Do you maybe have the library as a direct dependency in your projects composer.json?

No, only  "dhl/module-shipping-m2": "0.10.1",

**Comment by Napfton** [comment]
@ngolatka 

> @Napfton
> 
> > We have no non-DHL shipping method
> 
> Could you enable a dummy shipping method, NOT link it to DHL, and then create a test order yourself? Maybe use "Flat Rate" or "Free Shipping".
> 
> It would be interesting to see if the problem always occurs, regardless of our DHL module. You could do that before fighting with Composer to get the module updated (and then maybe find that the update didn't help).

Works like a charm. Used flatrate module and a test product, shipment created without errors.

**Comment by ngolatka** [comment]
> Works like a charm. Used flatrate module and a test product, shipment created without errors.

Thanks @Napfton However, I still have the same problem: I can't duplicate your issue. Works just fine here.

**Comment by Napfton** [comment]
@ngolatka how can I debug this issue further? debug in module is already enabled, nothing in the logs though...

**Comment by ngolatka** [comment]
I am a bit confused. The error message seems to come from Magento itself, more precisely from here

`app/code/Magento/Sales/Model/Order/Shipment/TrackRepository.php`

and it was added in [this commit](https://github.com/magento/magento2/commit/1b3304a2ce154307d88de77f96eb9bb029d16cb1).

The strange thing is: I don't see it anymore in the [current 2.2.8 code](https://github.com/magento/magento2/blob/2.2.8/app/code/Magento/Sales/Model/Order/Shipment/TrackRepository.php). How can you get this error in Magento 2.2.8 if the error message is not even present in the code at all?

... or am I missing something painfully obvious here?

**Comment by Napfton** [comment]
@ngolatka you mean this file https://github.com/magento/magento2/blob/2.2.8/app/code/Magento/Sales/Model/ResourceModel/Order/Shipment/Track.php right?

**Comment by ngolatka** [comment]
@Napfton Apparently I do. Seems I had a brainfart yesterday...

I read through your description again. Is your problem the missing tracking number in Magento, or are the DHL label PDF and the Magento shipment also not stored in your local DB?

I'm asking because the issue subject does not exactly match the bug description (storing tracking number vs. label in Magento).

**Comment by Napfton** [comment]
@ngolatka I just summarized it: nothing from DHL (neither tracking number nor the DHL label) is being stored in Magento. A Magento shipment document/slip is being generated, thats all. In the DHL portal everything looks fine. We now have to login to DHL to download the label and find out the tracking number.

**Comment by ngolatka** [comment]
@Napfton What confused me was this part:

> Expected behavior
> Tracking number stored in magento.

@powli and me will try to investigate why and when the problem occurs.

**Comment by powli** [comment]
Hey @Napfton,

unfortunately, I'm unable to reproduce the issue via these click paths in 2.2.8:
* create order, ship, directly create the label with the shipment (`Create Label` checkbox)
* create order, ship without the direct label, create shipment label from the shipment detail view

In general the error message is thrown by Magento in a workflow where we are no longer involved. Basically [our carrier model](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/Model/Shipping/Carrier.php#L275-L310) returns tracking number and the binary pdf data and Magento cares for storing the track later.
Do you have any third party extensions in place that could interfere here?

**Comment by Napfton** [comment]
Hey @powli sorry for the delay, I was traveling: No we do not have any other third party extension that does shipping. Actually no extension that interferes with order creation.

Any other place I could look?

**Comment by powli** [comment]
@Napfton are you able to reproduce the problem locally with an instance where you can step through the process with XDebug?

**Comment by JamesAllwood** [comment]
@Napfton - do you have M2E installed by any chance?

**Comment by Napfton** [comment]
@JamesAllwood sadly, we do. I can see where this is going. This shitty module, we are already trying other solutions, but its still installed and "working" (if you can call it this way) Is there a known issue with M2E and DHL shipping?

@powli  sorry forgot you, no, we currently have no staging/dev environment (missing ressources)

**Comment by Sendurrr** [comment]
> @JamesAllwood sadly, we do. I can see where this is going. This shitty module, we are already trying other solutions, but its still installed and "working" (if you can call it this way) Is there a known issue with M2E and DHL shipping?

Running M2ePro for 5 years with over 150.000 orders created by M2epro. 0 (ZERO !!) problems. Probably 1 of the best Extensions for Magento available.

**Comment by powli** [comment]
We had lots of support issues in the past with M2E, that came from imported orders circumventing the standard Magento order place flow and therefore not being picked up by our DHL shipping extension for processing with DHL (might have been Magento 1 too). That doesn't seem to be the case here though as you clearly properly try to process via DHL successfully and the data persistence within Magento fails.

I don't know if M2E reports the shipping status back to the platform synchronously, but if that is indeed the case, that might be a possible reason for this problem.

**Comment by JamesAllwood** [comment]
I've spent all day debugging it for it a client. Issue is that M2E seems to add a constraint somewhere (haven't traced where yet), that prevents a shipment and tracking being created at the same time. I could replicate this trying to ship the order in admin too.

 In my case (we're not using any dhl shipping), the solution is to create the shipment first and then add tracking number second. 

I just happened to find this issue as you were seeing the same error logged that I could see. 

It started happening for my client after upgrading to 2.2.8 too, and in the release notes, theres a mention of changes to tracking numbers.

I've not reported to M2E yet, but I will do.

**Comment by MarcusWolschon** [comment]
I reported a link to this issue to M2E support.
We can probably find the cause and a fix together.

M2E ticket number 112829

**Comment by m2epro** [comment]
It appears to be a bug on Magento v.2.2.8 and a solution for it can be found here: 
https://github.com/magento/magento2/commit/6b3195a9a66a2135b987d4f70cbcc72a9b02bf7a#diff-871f22641aa9a0ac64bcfde20e7df485

**Comment by m2epro** [comment]
@Napfton I'm sorry to read about your experience with m2e pro. If you have any issues, please free to contact our support.

**Comment by Napfton** [comment]
@m2epro haha, good one! Every time I ask support, in the end its a problem on our end or magento installation or magento code even! Barely ever its an M2E problem. We are currently evaluating another extension which is more expansive but looks promising.

anyway, that bug and the solution is working, closing this issue, thanks to all for the help!

**Comment by MarcusWolschon** [comment]
Note: That commit is tagged to have been included in 2.3.1 . So that version and later ones should be fine.

**Comment by Napfton** [comment]
It has a 2.3.1 tag, not sure if it will get backported to the 2.2.* branch

**Comment by MarcusWolschon** [comment]
Well, you can backport it and do a pull request.

**Comment by m2epro** [comment]
> @m2epro haha, good one! Every time I ask support, in the end its a problem on our end or magento installation or magento code even! Barely ever its an M2E problem. 

@Napfton , our support hates this as well!)) 

Quite often, our support engineers have to look into the code which is not related to m2e pro. And it is a really hard task as the developer must read and understand the code/logic of somebody else ( magento, 3rd party module, channel API, etc). Of course, we would prefer to find issues in our code and fix them right away - it takes much less time/resources.))

@Napfton , using your nickname, I was able to locate just one ticket with the issue. It was submitted in Nov 2018. 

I'm really sorry, that you have had such feeling that our support does not want to fix the issue. 

As a rule, during the investigation, the support engineer checks m2e code first of all, and if no issues detected, then provides with the recommendations/instructions.  

From my perspective, our support did a great job -  they performed deep investigation and provide details ( stack traces, screenshots of the logs with explanation, name of the magento events involved, the portion of code for testing,...) to help find the reason of the issue in magento. 

P.S. our support is still awaiting feedback if disabling the indexer for stock to be run on schedule helped to solve that issue.)
