### ISSUE TITLE
SOAP-ERROR: Encoding: Element 'majorRelease' has fixed value '1' (value '2' is not allowed)

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#6]
Hello @ngolatka 

since today we are getting the following (possible temporary) error (which is currently not listed in faq), while creating single shipping labels in M2 backend:

    Shipping labels could not be created: SOAP-ERROR: Encoding: Element 'majorRelease' has fixed value '1'     (value '2' is not allowed)

The last related commit did work before
https://github.com/netresearch/dhl-module-shipping-m2/commit/42cd90d4381ed73ca26cd3fc259dfdc9027f9faf

So this might be a change within the DHL Api or it is related to the last composer update.

Cheers
Jan

**Comment by ngolatka** [comment]
Hello @gewaechshaus 
yes, we have heard the same from lots of other merchants (starting today in the morning).

It seems as if something was changed at the DHL Webservice API. DHL is currently investigating what's going on.

The module for Magento 1 shows the same behavior, which means an issue in the modules is unlikely.

**Comment by gewaechshaus** [comment]
@ngolatka - thanks for keeping us informed!

**Comment by ngolatka** [comment]
@gewaechshaus 
DHL has just informed us that they found the problem. The DHL admins are working on the solution, and the webservice API should be up and running within the next few hours.

**Comment by ngolatka** [comment]
It has been confirmed that the DHL Webservice is running again.

Users who still experience issues should clear their WSDL cache.
