### ISSUE TITLE
Javascript errors on shipment creation page

### ISSUE THREAD

**Issue by kelada** [netresearch/dhl-module-shipping-m2#62]
**Bug description**
We are seeing multiple javascript issues on the "New shipment" page when enabling the DHL_Shipping module. When loading the page an error `Cannot read property 'select' of null` shows up. When clicking "Submit Shipment" an error `submitShipment is not defined` shows up in the javascript console and it is impossible to submit the shipment. Disabling the DHL_Shipping module solves the issue.

**Steps to reproduce**
To reproduce the problem:
1. Create an order
2. Open the order in magento in the dashboard and press the Ship button
3. Now your on the new shipment page, if you open the browser console, you will see the first error in the screenshot
4. When you press the Submit Shipment button you will see the second error in the screenshot and no shipment gets created

**Expected behavior**
No errors show show up in the browser console and a new shipment should get created.

**Screenshots / logs**
![Screenshot 2019-08-23 at 14 11 21](https://user-images.githubusercontent.com/30747386/63593636-aa181180-c5b4-11e9-8494-a1b7ed94ef96.png)

**Environment**
 - Magento version: 2.3.2
 - PHP version: 7.2.19
 - Module version: 0.10.3
 - No custom admin theme

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Hello @kelada I'm not sure if this is actually an issue in the DHL module. If this process wouldn't work, we should see a ton of support requests, because it would be a major blocker. But so far nobody else has contacted us with this description. Also, I don't see that problem on my local test system.

Things that come to mind: did you install the module completely and executed all the necessary steps? I mean especially the compilation, deployment of static content and so on.

Here's a [tutorial with the CLI commands](https://dhl.support.netresearch.de/support/solutions/articles/12000056624). Does that help?

**Comment by kelada** [comment]
Hi @ngolatka thanks for getting back to me.

>did you install the module completely and executed all the necessary steps?

We've scripted the setup of your module, please see it bellow, but I believe it's correct.

```
#!/bin/bash

set -eo pipefail

while ! mysqladmin ping -h"${MYSQL_HOSTNAME}" --silent; do
  echo "Waiting on database connection.."
  sleep 2
done

echo "Configuring Magento configuration for setup"
bin/magento setup:config:set -q \
  --db-host=$MYSQL_HOSTNAME \
  --db-name=$MYSQL_DATABASE \
  --db-user=$MYSQL_USERNAME \
  --db-password=$MYSQL_PASSWORD \
  --cache-backend=redis \
  --cache-backend-redis-server=$REDIS_SERVER \
  --cache-backend-redis-port=$REDIS_PORT \
  --cache-backend-redis-password=$REDIS_PASSWORD \
  --cache-backend-redis-db=0 \
  --page-cache=redis \
  --page-cache-redis-server=$REDIS_SERVER \
  --page-cache-redis-port=$REDIS_PORT \
  --page-cache-redis-password=$REDIS_PASSWORD \
  --page-cache-redis-db=1 \
  --session-save=redis \
  --session-save-redis-host=$REDIS_SERVER \
  --session-save-redis-port=$REDIS_PORT \
  --session-save-redis-password=$REDIS_PASSWORD \
  --session-save-redis-db=2 \
  --session-save-redis-log-level=3 \
  --key=$ENCRYPTION_KEY

echo "Installing Magento"
bin/magento setup:install -q \
  --base-url=$BASE_URL \
  --admin-firstname=$ADMIN_FIRSTNAME \
  --admin-lastname=$ADMIN_LASTNAME \
  --admin-email=$ADMIN_EMAIL \
  --admin-user=$ADMIN_USERNAME \
  --admin-password=$ADMIN_PASSWORD \
  --language=$LANGUAGE \
  --currency=$CURRENCY \
  --timezone=$TIMEZONE \
  --backend-frontname=$BACKEND_FRONTNAME \
  --use-rewrites=1

echo "Importing Magento configuration from config.php"
mv ./app/etc/config.tmp.php ./app/etc/config.php
bin/magento app:config:import -q -n

echo "Upgrading extensions"
bin/magento setup:upgrade -q

echo "Starting code compilation"
bin/magento setup:di:compile -q

if [ "$RUNTYPE" == "development" ]; then
  echo "Switching to development mode"
  bin/magento deploy:mode:set developer -q

  echo "Enable php error reporting"
  echo "display_errors = On" >> /usr/local/etc/php/php.ini
else

  echo "Switching to production mode"
  bin/magento deploy:mode:set production -s -q

  echo "Disable php error reporting"
  echo "display_errors = Off" >> /usr/local/etc/php/php.ini

  echo "Deploying static content"
  bin/magento setup:static-content:deploy $SUPPORTED_LANGUAGES -q

  echo "Setting production mode permissions"
  mkdir -p app/code app/etc var/view_preprocessed pub/static generated/metadata generated/code
  find app/code var/view_preprocessed vendor pub/static app/etc generated/code generated/metadata \( -type f -or -type d \) -exec chmod u-w {} +
  chmod o-rwx app/etc/env.php
  chmod u+x bin/magento
fi

echo "Starting php-fpm"
php-fpm -c /usr/local/etc/php/php.ini
```

**Comment by ngolatka** [comment]
One thing I don't see in the above script is flushing the caches
`bin/magento cache:flush`

which should normally be done before
`bin/magento setup:di:compile`

Does that make a difference? If it doesn't, it will get a bit hard to help you, because I still don't see the issue on my system (and I work with it every day).
