### ISSUE TITLE
Import failed: Notice: Array to string conversion at app:config:import

### ISSUE THREAD

**Issue by HenKun** [netresearch/dhl-module-shipping-m2#63]
**Bug description**
Import of config is not possible due to this module.

**Steps to reproduce**
To reproduce the problem:
1. Install the module in v 0.10.3 on a vanilla Magento 2.3.2 install
2. On CLI export (dump) the config via `app:config:dump`
3. Import the config via `app:config:import` again

**Expected behavior**

`app:config:import` is successfull

**Actual behavior**

1. `app:config:import` as well as `setup:upgrade` fail with error:

> Import failed: Notice: Array to string conversion in /home/cloudpanel/htdocs/nebelkind.dev/vendor/magento/framework/App/Config/Value.php on line 100

Surprisingly, that is caused by `bcs_sandbox_account_participations` but not by the `bcs_account_participations` setting.  The only difference between these both is, that `bcs_account_participations` is defined in system.xml, with a value given in config.xml, whereas `bcs_sandbox_account_participations` is only defined in config.xml. This way, `bcs_sandbox_account_participations` is missing the frontend model. By setting the frontend model to `bcs_sandbox_account_participations` in system.xml, identically to `bcs_account_participations` the issue disappears.

**Screenshots / logs**

**Environment**
 - Magento version: 2.3.2
 - PHP version: 7.2
 - Module version: 0.10.3

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Hello @HenKun that is indeed an interesting problem. You are the first who reported this.

Our team will check what is going on here and will then provide feedback here.

_(ticket: DHLVM2-368)_

**Comment by HenKun** [comment]
I guess there aren't many who use this module and also use the shared config feature of magento. Or they don't use the config dump feature and fill the config.php via CLI manually.

**Comment by attilan** [comment]
Hi @ngolatka, I have the same issue on m2.3.2, do you have any update on this?

**Comment by ngolatka** [comment]
@HenKun wrote:
> I guess there aren't many who use this module and also use the shared config feature of magento. Or they don't use the config dump feature and fill the config.php via CLI manually.

Because you are the first one who ever reported this issue (to my knowledge), I tend to agree with your assumption.

@attilan 
Sorry for the long delay. I was out of the office for some time. We'll take this into consideration for future versions (for which we don't have an ETA yet, sorry).

**Comment by powli** [comment]
Fix for this is included in [0.11.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.11.0)
