### ISSUE TITLE
Specify sandbox mode settings as system specific

### ISSUE THREAD

**Issue by HenKun** [netresearch/dhl-module-shipping-m2#64]
**Feature description**
There is the possibility to specify which settings should be general, system specific or sensitive. See [Magento docs](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.html). It would be of benefit if some settings, e.g. Sandbox mode is defined as system-specific so that `app:config:dump` directly writes the setting to the env.php instead of config.php file. 

**Reason**
It would improve the readability of the config.php since sandbox setting are overridden manually in env.php, so they are not used from config.php at all. Second, If not specified in env.php, currently it is not possible to change the sandbox mode in admin panel manually, since the setting in config.php prevents it. Third, it is semantically more correct, since sandbox mode is indeed a system specific setting.

It is not an urgent feature, because, as stated, can be overriden in env.php manually.

**Comment by ngolatka** [comment]
Thanks @HenKun This is something we will take into consideration for upcoming modules.

**Comment by ngolatka** [comment]
Closed because `dhl-module-shipping-m2` is not maintained anymore.
