### ISSUE TITLE
Publish on packagist

### ISSUE THREAD

**Issue by amenk** [netresearch/dhl-module-shipping-m2#67]
**Feature description**

Please publish the module on packagist

**Reason**
Installation via composer works easier

**Comment by MarcusWolschon** [comment]
Note that the installation via Composer works fine from named releases or named branches on Github.
It does require the extra step of telling composer about the github repository URL as source for the package.
See here:
https://stackoverflow.com/questions/31743139/how-to-add-non-public-repositories-from-command-line-with-composer

**Comment by amenk** [comment]
Yes, I know, 

> It does require the extra step of telling composer about the github repository URL as source for the package.

Exactly this should be avoided.

For example, if you have many packages which are not on packagist.org, composer update takes ages, because each GIT Repo has to be scanned.

**Comment by mam08ixo** [comment]
The composer repository for this module is https://repo.magento.com/

See [DHL Shipping on Magento Marketplace](https://marketplace.magento.com/dhl-module-shipping-m2.html).

Thanks

**Comment by amenk** [comment]
Okay, that makes sense - then we should clarify the readme.

**Comment by ngolatka** [comment]
Indeed, the readme could be clarified a bit. The next version will include that.

As a hint for future people who might stumble over this: the Knowledge Base also has an article that explains the installation with Composer using repo.magento.com: https://dhl.support.netresearch.de/support/solutions/articles/12000056624

_(internal ticket: DHLVM2-369)_
