### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by sprankhub** [netresearch/dhl-module-shipping-m2#68]
**Feature description**
This module should support PHP 7.3.

**Reason**
Magento 2.3.3 now supports PHP 7.3.

**Comment by ngolatka** [comment]
@sprankhub
Yes sir, it should, and it will do so quite soon, in the next version.

_(internal ticket DHLVM2-363)_

**Comment by powli** [comment]
Done with [0.11.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.11.0)
