### ISSUE TITLE
DHL extra services are not shown

### ISSUE THREAD

**Issue by kolaente** [netresearch/dhl-module-shipping-m2#69]
**Bug description**
DHL extra services popup is not shown in checkout.

At first, it was not shown in a different checkout module, then I tried to reproduce it with the default checkout, and it didn't work either.

I got it somewhat working by adding a second shipping method and then switching between the two, until it eventually appeared. This is not a real solution for us, since the shop only has one shipping method.

**Steps to reproduce**
To reproduce the problem:
1. Go to checkout
2. Enter an Address
3. Get the "DHL extra services" popup to add additional services. This does not work.

This is how it looks (default checkout):

![grafik](https://user-images.githubusercontent.com/13721712/71878708-9963d480-312c-11ea-8e51-816818f90aa2.png)

**Expected behavior**

This is how it should look in the checkout:

![grafik](https://user-images.githubusercontent.com/13721712/71878703-949f2080-312c-11ea-916d-dbc20019f71d.png)

**Environment**
 - Magento version: 2.3.3
 - PHP version: 7.1.33
 - Module version: 0.11.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Thanks for reporting this, @kolaente I'll check what's going on.

**Comment by ngolatka** [comment]
@kolaente I tried several times with different configurations, but I can't duplicate the issue. What I did is this:
* Enable only one shipping method (Flat Rate) and link it to DHL Shipping
* Enable DHL services (Wunschtag, Wunschort, Wunschzeit etc.) in the configuration
* Go through checkout and enter a valid address
* Wait for the shipping method to get loaded (happens automatically)

Result: shipping method appears, including the yellow DHL box with the various services.

I used M 2.3.3, DHL Shipping 0.11.0 and PHP 7.2.26 (latter shouldn't really matter here).

Do you see any errors in the Magento or PHP logs during checkout?

**Comment by kolaente** [comment]
@ngolatka Thank you for checking.

I did not see any errors in either the magento logs or my browser console, however I could see it making multiple requests to `/services/production/rest/checkout/<postcode>/availableServices?startDate=2020-01-08`, so at least we can tell it is loaded correctly and doing something.

The whole issue is a bit strange though, I managed to reproduce it somehow, but not consistently. Sometimes it would work, sometimes not. I did not find out why yet.

**Comment by kolaente** [comment]
Is there a reason to initially hide the extra stuff and only show it under certain conditions? What are these conditions? Would you accept a pr with a configurable option to always show it?

**Comment by kolaente** [comment]
It looks like this was a configuration issue on our side. Apparently, all extra services were disabled: 
![image](https://user-images.githubusercontent.com/13721712/71962010-e01f0080-31f8-11ea-98d3-2b55ed6909fa.png)

Hence, the extra services field was not shown at all. I've re-enabled them and it works like it should, also with the external checkout module.

**Comment by ngolatka** [comment]
@kolaente Good to know it works now!.

I assumed the configuration of the extra services would already be correct (i.e. enabled), because you said:
> I got it somewhat working by adding a second shipping method and then switching between the two
