### ISSUE TITLE
Standard package sizes [feature wish]

### ISSUE THREAD

**Issue by gewaechshaus** [netresearch/dhl-module-shipping-m2#7]
Hey,

at first let me say thanks for creating this nice module. Everything works well oob. During our daily backend work we are missing the following feature:

Each time you ship out a package, you need to write down the packages size. As we are working with many different sizes, you can only remember the most ordered sizes. In conclusion you have to look in another window to grab the right package size. So if there would be a feature to crud packages sizes and apply them by a dropdown(or more advanced by rules like weight or volumetric weight) in the label creation popup, our work would be much easier.

Cheers
Jan

**Comment by ngolatka** [comment]
Hello @gewaechshaus 
unless I'm mistaken, the fields for length x height x width come from Magento Core, not from our module.

Also, the fields are not required. You can leave them empty. As far as we know, most merchants do that.
