### ISSUE TITLE
Release Version 1.0.0

### ISSUE THREAD

**Issue by sprankhub** [netresearch/dhl-module-shipping-m2#71]
**Change description**
I would like to have a stable release `1.0.0` of this module.

**Reason**
Having a `0.*` version just looks unstable and the module is not unstable I think ;-) Additionally, with the current versioning scheme, one does not get all feature updates.

**Additional context**
We required the module when the current version was still `0.10.3`. Hence, we have `"dhl/module-shipping-m2": "^0.10.3"` as a requirement in our `composer.json`, because the version was `0.*`. Hence, we would never get `0.11.0` until we explicitly update our requirement. This is a pity, because I would love to have feature updates.
Having version `1.0.0` would lead to a version constraint of `^1.0`, so that one would get `1.1` "automatically".

**Comment by moehrenzahn** [comment]
Hi @sprankhub,

thanks for your feedback, I completely understand your problem.

However, there will not be a 1.0.0 release of this package in the foreseeable future. There are also no feature updates planned, this module is considered "legacy".

As you may know, we are working on getting a new shipping extension out the door. I can't give you an ETA except that it will be released soon-ish (watch [this space](https://github.com/netresearch/dhl-module-carrier-paket)).

This new DHL Shipping will be released as the 1.0.0 you wish for, but it will be a separate Magento 2 extension with a separate GitHub repository.
