### ISSUE TITLE
Shipping labels could not be created: Unauthorized

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-module-shipping-m2#72]
Since this morning we are getting:

"Shipping labels could not be created: Unauthorized" 

Exception Logs.

[2020-03-31 10:51:27] main.ERROR: HTTP/1.1 401 Unauthorized
Date: Tue, 31 Mar 2020 10:51:27 GMT
Server: Apache
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-XSS-Protection: 1; mode=block
X-DNS-Prefetch-Control: off
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: default-src 'none'; script-src 'none'; frame-src 'none'; object-src 'none'
WWW-Authenticate: Basic realm="CIG Production Services"
Content-Length: 381
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
 {"exception":"[object] (Dhl\\Shipping\\Webservice\\Exception\\ApiCommunicationException(code: 0): API communication failed at /var/www/share/meevo.io/releases/15/vendor/dhl/lib-shipping-mx/Webservice/Adapter/BcsAdapter.php:136, SoapFault(code: 0): Unauthorized at /var/www/share/meevo.io/releases/15/vendor/dhl/module-shipping-m2/Webservice/Client/BcsSoapClient.php:144)"} []
[2020-03-31 10:51:27] main.ERROR:  {"exception":"[object] (Dhl\\Shipping\\Webservice\\Exception\\ApiCommunicationException(code: 0): API communication failed at /var/www/share/meevo.io/releases/15/vendor/dhl/lib-shipping-mx/Webservice/Adapter/BcsAdapter.php:136, SoapFault(code: 0): Unauthorized at /var/www/share/meevo.io/releases/15/vendor/dhl/module-shipping-m2/Webservice/Client/BcsSoapClient.php:144)"} []

in the magento backend when trying to create shipping label... I changed the credentials and everthing seems fine... has anything been changed on DHL API side?

**Comment by ngolatka** [comment]
Hello @simonmaass 
We are aware of this problem and are in contact with DHL about possible solutions. As soon as we know more, we'll post it here.

**Comment by MerikMag** [comment]
Also facing this critical issue.

**Comment by ngolatka** [comment]
@MerikMag 
Yes, I'm sure you are. Everyone using this extension for Magento 2 is affected.

**Comment by Sendurrr** [comment]
it's working again.

**Comment by MerikMag** [comment]
I can confirm. It is working again. Thanks for the quick fix.

**Comment by ngolatka** [comment]
Thank y'all for confirming that.
FYI: the problem was resolved by the DHL IT team, not by us (the extension developers).

**Comment by ngolatka** [comment]
Sorry to say that the problem has appeared again. You need a new token to be able to access the DHL API. The existing token has been revoked and cannot be reactivated.

### How to fix this
**Option 1:**
Update the DHL Shipping module to the [latest version](https://github.com/netresearch/dhl-module-shipping-m2/releases). This will update the token in your system.

**Option 2**
If you can't update the module: get the new token and instructions how to store it manually by [opening a support ticket](https://dhl.support.netresearch.de/support/tickets/new).

Note: the token is not your DHL username and password. Don't try to change those, it won't fix the problem.

**Comment by simonmaass** [comment]
@ngolatka what do you mean with token? there is only user and password:

![Unbenannt](https://user-images.githubusercontent.com/32599710/78228095-9465b580-74ce-11ea-86e1-a6081727f577.png)

**Comment by ngolatka** [comment]
@simonmaass The token is not your DHL user and password. It is basically an additional authentication layer of the DHL API, which you normally don't have to configure yourself.

**Comment by simonmaass** [comment]
Where is that token being stored? Or where will i need to provide it in magento?

**Comment by ngolatka** [comment]
Please read my message again.

> To get the new token **and detailed instructions**, please open a support ticket.

**Comment by simonmaass** [comment]
Well thank you so much - you have been more than helpful!

**Comment by ngolatka** [comment]
I'm closing this issue for now. If anyone else runs into this problem, please see [my above comment](https://github.com/netresearch/dhl-module-shipping-m2/issues/72#issuecomment-607704600) for the solution options.

If you run into problems, you can [open a support ticket here](https://dhl.support.netresearch.de/support/tickets/new).
