### ISSUE TITLE
Fatal error: Interface 'Dhl\Shipping\Webservice\Client\BcsSoapClientInterface' not found in /var/www/html/app/code/Dhl/Shipping/Webservice/Client/BcsSoapClient.php on line 38

### ISSUE THREAD

**Issue by Alexkwang** [netresearch/dhl-module-shipping-m2#73]
Fatal error: Interface 'Dhl\Shipping\Webservice\Client\BcsSoapClientInterface' not found in /var/www/html/app/code/Dhl/Shipping/Webservice/Client/BcsSoapClient.php on line 38

**Comment by mam08ixo** [comment]
Please install the module properly with its dependencies using [composer](https://getcomposer.org/). See #22
