### ISSUE TITLE
Hard validation error occured. Der angegebene Service ist nicht bekannt.

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-module-shipping-m2#74]
Since this morning we are getting the follow error:

"Shipping labels could not be created: Hard validation error occured. Der angegebene Service ist nicht bekannt. Der angegebene Service ist nicht bekannt."

![Unbenannt](https://user-images.githubusercontent.com/32599710/80952737-6ee40880-8dfa-11ea-95e8-e893456b401b.png)

**Comment by mam08ixo** [comment]
Hi @simonmaass,

please check the logs if billing number (`returnShipmentAccountNumber`) and return address (`ReturnReceiver`) are properly set.

Also make sure that the billing number used for returns is available in your contract (compare DHL Business Customer Portal).

**Comment by ngolatka** [comment]
Tutorial for the above is here: https://dhl.support.netresearch.de/support/solutions/articles/12000024659

Make sure to choose the correct line (product), in your case the one that says "...Retoure" or "...Return".

If all that doesn't help, call DHL and ask them to check if the desired service is actually enabled.

**Comment by simonmaass** [comment]
@mam08ixo @ngolatka thnx for the help - all works again!
