### ISSUE TITLE
Free Shipping Option not working with DHL Shipping

### ISSUE THREAD

**Issue by max2play** [netresearch/dhl-module-shipping-m2#75]
**Bug description**
Problem occurs when using DHL Shipping (bound to tablerates) and having set up Free Shipping in the Shipping Methods for Orders above 100€. When a customer uses Free Shipping in the Checkout a DHL Label cannot be printed as the order is not connected to DHL Shipping.

**Steps to reproduce**
To reproduce the problem:
1. Admin: Set up Free Shipping and DHL Shipping with fixed fee or tablerates
2. Customer: Checkout meeting the Free Shipping requirement and choose Free Shipping from the Shipping options
3. Admin: Try to create a DHL Shipping Label for the Shipment -> not possible

**Expected behavior**
You can create DHL Shipping Labels independently of the choosen Shipping Method - or at least when Free Shipping is selected by the customer as this is just a way of setting the Shipping Fee to zero, but no changing the way the parcel gets shipped.

**Environment**
 - Magento version: 2.3.5
 - PHP version: 7.3.11
 - Module version: 1.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [x] Yes, but couldn't find anything

**Comment by mam08ixo** [comment]
Hi @max2play,

this package has no version 1.0 so I assume you reference its [replacement module](https://marketplace.magento.com/dhl-shipping-m2.html).

To fulfill your requirement, set up free shipping via cart price rules. Do not use the built-in _Free Shipping_ method.

**Comment by MarcusWolschon** [comment]
> Hi @max2play,
> 
> this package has no version 1.0 so I assume you reference its [replacement module](https://marketplace.magento.com/dhl-shipping-m2.html).
> 
> To fulfill your requirement, set up free shipping via cart price rules. Do not use the built-in _Free Shipping_ method.

Please don't link to Magento marketplace but to the Github repository of the replacement.
https://github.com/netresearch/dhl-shipping-m2

**Comment by ngolatka** [comment]
@MarcusWolschon The Magento Marketplace is the official point for distribution. Repos on Github are provided as an addition, for extra convenience, or if something is not available on the Marketplace anymore.

**Comment by MarcusWolschon** [comment]
But the Marketplace has no issue tracker and you are writing to people who are already on the Github issue tracker, checking out the status of known issues.

**Comment by ngolatka** [comment]
Closed because `dhl-module-shipping-m2` is not maintained anymore.
