### ISSUE TITLE
Exception on deactivated Service Option preferredTime

### ISSUE THREAD

**Issue by mautz-et-tong** [netresearch/dhl-module-shipping-m2#76]
**Bug description**
The DHL Module throws randomly the Exception
"Service with code preferredTime was removed due to error. Message: There are no results for this service."

We have completly deactivated this Options around preferred Time.

Error is thrown in CompositeOptionProvider line 79

**Steps to reproduce**
No steps to reproduce. Error occurs randomly. Module is activated and normally setup and working fine beside of this error. Preferred Time options are disabled

**Expected behavior**
The preferred time service should be ignored, no exception should be thrown.

**Screenshots / logs**
"main.WARNING: Service with code preferredTime was removed due to error. Message: There are no results for this service." in system.log

**Environment**
- Magento 2.3.5
- PHP 7.3.18
- DHL Module 0.11.1

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [ x] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by mam08ixo** [comment]
Hi @mautz-et-tong,

first of all, this module version is no longer maintained. Please migrate to [DHL Shipping v1.1.0](https://marketplace.magento.com/dhl-shipping-m2.html).

My first guess is that the "randomness" comes from some older quotes/orders, created at a time when _Preferred Time_ was still available. DHL Paket does no longer offer this service, so any attempts to fetch service options (=possible time slots) will fail, resulting in given error. In theory, this log entry should not occur for new checkout processes; the number of log entries will decrease over time.

If I understand you correctly, the error does not lead to a service disruption, it's "only" annoying. I kindly ask you to ignore these messages. There is nothing we or you can do about it but wait until there are no more traces of the _Preferred Time_ service left in the service data.

**Comment by mautz-et-tong** [comment]
Migrated to the Marketplace Version.

**Comment by MarcusWolschon** [comment]
> Hi @mautz-et-tong,
> 
> first of all, this module version is no longer maintained. Please migrate to [DHL Shipping v1.1.0](https://marketplace.magento.com/dhl-shipping-m2.html).

Please don't link to Magento marketplace but to the Github repository of the replacement.
https://github.com/netresearch/dhl-shipping-m2
