### ISSUE TITLE
Magento 2.4

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-module-shipping-m2#77]
**Bug description**
After upgrading to 2.4 I get the following errors when trying to create a shipment:

![image](https://user-images.githubusercontent.com/32599710/91415506-6f435c00-e84e-11ea-86d1-e0f5fc5971d8.png)

**Steps to reproduce**
To reproduce the problem:
1. Create Order
2. Click on "Ship"
3. See error message when clicking on "Submit Shipment"

**Environment**
 - Magento version: 2.4
 - PHP version: 7.4
https://marketplace.magento.com/dhl-shipping-m2.html
 - Module version: 1.1.0

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [ ] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Hello @simonmaass , as the [readme](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/README.md) states:
> Warning: This extension is no longer supported and should not be used.

This extension won't be updated for compatibility with Mage 2.4, sorry.

However, if you are referring to the [new DHL module](https://github.com/netresearch/dhl-shipping-m2), then please note [this issue](https://github.com/netresearch/dhl-shipping-m2/issues/8).
