### ISSUE TITLE
Cron sometimes doesn't create Shipping Labels

### ISSUE THREAD

**Issue by emmathepossum** [netresearch/dhl-module-shipping-m2#78]
**Question**
In one of our shops we have the following problem:
Every couple of days the DHL cronjob seems to not work properly and does not generate any Shipping Labels for the entire batch of orders, however the orders are processed correctly in every other way. This leads to the problem that the shop owner can't bulk print the Shipping Labels like usual but has to manually create them. The "Retry Failed Shipments" Option in the Backend unfortunately does not fix this issue, at best it only happens less frequently.

Have you ever encountered anything like this and maybe could help us to find the source of the problem?

**Additional context**
Unfortunately there are absolutely no errors in the log, making it more difficult to track down the problem. The entire log is just filled with success messages, we even enabled the "Info" stage of logging. Here's the request of one of the orders where no shipping label was created:
(I removed the other Shipments from this request because it was just the same multiple times over)
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://dhl.de/webservice/cisbase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://dhl.de/webservices/businesscustomershipping/3.0">
    <SOAP-ENV:Header>
        <ns1:Authentification>
            <ns1:user>[hidden]</ns1:user>
            <ns1:signature>[hidden]</ns1:signature>
        </ns1:Authentification>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <ns2:CreateShipmentOrderRequest>
            <Version xsi:type="ns1:Version">
                <ns1:majorRelease>3</ns1:majorRelease>
                <ns1:minorRelease>0</ns1:minorRelease>
            </Version>
            <ShipmentOrder>
                <sequenceNumber>0</sequenceNumber>
                <Shipment>
                    <ShipmentDetails>
                        <product>V01PAK</product>
                        <ns1:accountNumber>[hidden]</ns1:accountNumber>
                        <customerReference>100170954</customerReference>
                        <shipmentDate>2020-11-07</shipmentDate>
                        <ShipmentItem>
                            <weightInKG>2</weightInKG>
                            <lengthInCM>20</lengthInCM>
                            <widthInCM>30</widthInCM>
                            <heightInCM>2</heightInCM>
                        </ShipmentItem>
                    </ShipmentDetails>
                    <Shipper>
                        <Name>
                            <ns1:name1>[Shop]</ns1:name1>
                            <ns1:name2></ns1:name2>
                        </Name>
                        <Address>
                            <ns1:streetName>[Street]</ns1:streetName>
                            <ns1:streetNumber>[Number]</ns1:streetNumber>
                            <ns1:zip>[Zip]</ns1:zip>
                            <ns1:city>[City]</ns1:city>
                            <ns1:province>[Province]</ns1:province>
                            <ns1:Origin>
                                <ns1:countryISOCode>DE</ns1:countryISOCode>
                            </ns1:Origin>
                        </Address>
                        <Communication />
                    </Shipper>
                    <Receiver>
                        <ns1:name1>[Customer]</ns1:name1>
                        <Address>
                            <ns1:name2></ns1:name2>
                            <ns1:streetName>[Street]</ns1:streetName>
                            <ns1:streetNumber>[Number]</ns1:streetNumber>
                            <ns1:addressAddition></ns1:addressAddition>
                            <ns1:zip>[Zip]</ns1:zip>
                            <ns1:city>[city]</ns1:city>
                            <ns1:province>[Province]</ns1:province>
                            <ns1:Origin>
                                <ns1:countryISOCode>DE</ns1:countryISOCode>
                            </ns1:Origin>
                        </Address>
                        <Communication>
                            <ns1:email>[email]</ns1:email>
                        </Communication>
                    </Receiver>
                </Shipment>
            </ShipmentOrder>
            <labelResponseType>B64</labelResponseType>
        </ns2:CreateShipmentOrderRequest>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

The shop also uses decimal quantities which has already caused a lot of problems with several other modules, but we couldn't find any relations to that.

On the most recent batch of failed shipments we were able to locate this error when trying to manually create a shipment over the magento backend, but only for the *first and last* order of the batch, all the ones in between worked.

```
Label could not be created: Hard validation error occured. Bitte geben Sie eine Postnummer an. Die verwendete Postnummer ist nicht gültig. Bitte geben Sie eine gültige Postnummer an. Der Ort ist zu dieser PLZ nicht bekannt. Die Sendung ist trotzdem leitcodierbar und es wurde ein Versandschein erzeugt.
```
I'm putting this in as a question because we don't have enough info to clearly identify this as a bug in the module. My best bet is some problem on the DHL side which then just doesn't answer our request resulting in no error and unresolved shipments.

**FAQ**
Has the [Knowledge Base](http://dhl.support.netresearch.de) been checked for a solution?
- [X] Yes, but couldn't find anything
- [ ] Yes, but solution did not work

**Comment by ngolatka** [comment]
Hello @dwirt , I'd like to point out one important thing in the [readme of this project](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/README.md):

> Warning: This extension is no longer supported and should not be used. You can find the official replacement extension [here on GitHub](https://github.com/netresearch/dhl-shipping-m2).

**Comment by emmathepossum** [comment]
Oh sorry, my bad. We are using the new extension with version 1.0.1, seems I just posted in the wrong repository.
Apparently there is also now a 1.3.0 Version out, I'll try updating the module to a newer version, hopefully that fixes it.
