### ISSUE TITLE
Composer install - White page after installation

### ISSUE THREAD

**Issue by ghost** [netresearch/dhl-module-shipping-m2#9]
Hello,
I just installed the module with composer and did every like the instruction said. The installation gone through without any problems.

After enabling and successfully doing all steps i got a white page on Configuration > Sales > Shipping methods.

How do we fix this issue ?

**Comment by ngolatka** [comment]
@Streetec I don't think this is an issue in the extension itself. Please also note my [general infos on what issues are for](https://github.com/netresearch/dhl-module-shipping-m2/issues/4).

That said, please take a look at the various log files and check for errors that occur when you try to open the page. That should tell you where to look next.

If you can't find the cause, please [contact our support](http://dhl.support.netresearch.de/support/tickets/new).
